---
settings:
  name: Astra Control Service
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  filter:
    label: Ou du fournisseur cloud
    default: Tous les fournisseurs cloud
    options:
    - name: Amazon Web Services
      alias: Amazon Web Services
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  rss_page: release-notes/whats-new.html
  langs: fr-fr,us-en,ja-jp,zh-cn,zh-tw,ko-kr,de-de
sidebar:
  entries:
  - title: Documentation sur le service Astra Control
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: use
  - title: Automatisez avec l'API REST Astra Control
    url: "/automation.html"
  - section: learn
  - section: support
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Découvrez le service Astra Control
      url: "/get-started/intro.html"
    - title: Démarrage rapide
      url: "/get-started/quick-start.html"
    - title: FAQ
      url: "/get-started/faq.html"
  - title: Utilisez le service Astra Control
    links:
    - title: Gestion des applications
      url: "/use/manage-apps.html"
    - title: Protégez vos applications
      url: "/use/protect-apps.html"
    - title: Migrer une application
      url: "/use/clone-apps.html"
    - title: Configurez la facturation
      url: "/use/set-up-billing.html"
  - title: Utilisez l'API REST Astra Control
    links:
    - title: Commencez
      url: https://docs.netapp.com/us-en/astra-automation/get-started/before_get_started.html
    - title: Référence API
      url: https://docs.netapp.com/us-en/astra-automation/reference/api_reference.html
    - title: Workflows API
      url: https://docs.netapp.com/us-en/astra-automation/workflows/workflows_before.html
  - title: Didacticiels de démonstration
    links:
    - title: Vidéos sur le service Astra Control
      url: "/get-started/videos.html"
  - title: Centre de contrôle Astra
    links:
    - title: Présentation du centre de contrôle Astra
      url: https://docs.netapp.com/us-en/astra-control-center/concepts/intro.html
    - title: Quoi de neuf
      url: https://docs.netapp.com/us-en/astra-control-center/release-notes/whats-new.html
    - title: Démarrage rapide
      url: https://docs.netapp.com/us-en/astra-control-center/get-started/quick-start.html
  - title: Descriptions de solutions
    links:
    - title: DataStax Enterprise Apache Cassandra avec Astra Control
      url: https://cloud.netapp.com/hubfs/SB-4134-0321-DataStax-Cassandra-Guide%20(1).pdf
    - title: DBaaS avec Astra Control
      url: https://cloud.netapp.com/hubfs/SB-4122-0221-PostgresSQL-DBaaS-with-Astra%20(2).pdf
    - title: MySQL DBaaS avec Astra Control
      url: https://cloud.netapp.com/hubfs/SB-4110-0221-MySQL-Astra%20(2).pdf
    - title: Simplifiez la gestion du cycle de vie Jenkins
      url: https://cloud.netapp.com/hubfs/SB-4100-Jenkins%20(2).pdf
  - title: Communauté sur les blogs
    links:
    - title: Canal de discorde Astra
      url: https://discord.gg/NetApp
    - title: Blog Astra Control
      url: https://cloud.netapp.com/blog/topic/astra
    - title: Astra Control – qui simplifie la gestion des données d'application pour
        le cloud hybride
      url: https://cloud.netapp.com/blog/blg-astra-control-simplifying-kubernetes-application-data-management-for-the-hybrid-cloud
    - title: Kubernetes Hub sur Cloud Central
      url: https://cloud.netapp.com/kubernetes-hub
product-family:
  name: Astra
  repo: astra-family
  sidebar_label: Toute la documentation Astra
