---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: 'Ajoutez et supprimez des informations d"identification du fournisseur cloud de votre compte à tout moment. Astra Control utilise ces identifiants pour provisionner des ressources en votre nom.' 
---
= Ajouter et supprimer des informations d'identification
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


Ajoutez et supprimez des informations d'identification du fournisseur cloud de votre compte à tout moment. Astra Control utilise ces identifiants pour détecter un cluster Kubernetes et les applications sur le cluster, et provisionner les ressources en votre nom.

Notez que tous les utilisateurs d'Astra Control partagent les mêmes informations d'identification.



== Ajouter des informations d'identification

La façon la plus courante d'ajouter des informations d'identification à Astra Control est de gérer les clusters, mais vous pouvez également ajouter des informations d'identification à partir de la page compte. Les identifiants seront ensuite disponibles pour choisir lors de la gestion de clusters Kubernetes supplémentaires.

ifdef::aws[]

* Pour Amazon Web Services, vous devez disposer de la sortie JSON des informations d'identification du compte IAM utilisé pour créer le cluster. link:../get-started/set-up-amazon-web-services.html["Découvrez comment configurer un utilisateur IAM"].


endif::aws[]

ifdef::gcp[]

* Pour GKE, vous devez disposer du fichier de clé de compte de service pour un compte de service disposant des autorisations requises. link:../get-started/set-up-google-cloud.html["Découvrez comment configurer un compte de service"].


endif::gcp[]

ifdef::azure[]

* Pour AKS, vous devez disposer du fichier JSON qui contient la sortie de l'interface de ligne de commande Azure lorsque vous avez créé le principal de service. link:../get-started/set-up-microsoft-azure-with-anf.html["Découvrez comment configurer un principal de service"].
+
Vous aurez également besoin de votre ID d'abonnement Azure, si vous n'avez pas ajouté le fichier JSON.



endif::azure[]

.Étapes
. Sélectionnez *compte > informations d'identification*.
. Sélectionnez *Ajouter des informations d'identification*.


ifdef::azure[]

. Sélectionnez *Microsoft Azure*.


endif::azure[]

ifdef::gcp[]

. Sélectionnez *Google Cloud Platform*.


endif::gcp[]

ifdef::aws[]

. Sélectionnez *Amazon Web Services*.


endif::aws[]

. Saisissez un nom pour les informations d'identification qui les distinguent des autres informations d'identification dans Astra Control.
. Indiquez les informations d'identification requises.


ifdef::azure[]

. *Microsoft Azure*: Fournissez Astra Control avec des détails sur votre principal de service Azure en téléchargeant un fichier JSON ou en collant le contenu de ce fichier JSON à partir de votre presse-papiers.
+
Le fichier JSON doit contenir la sortie de l'interface de ligne de commandes Azure lorsque vous avez créé le principal de service. Il peut également inclure votre identifiant d'abonnement afin qu'il soit automatiquement ajouté à Astra Control. Sinon, vous devez saisir manuellement l'ID après avoir fourni le fichier JSON.



endif::azure[]

ifdef::gcp[]

. *Google Cloud Platform*: Fournir le fichier de clé de compte de service Google Cloud soit en téléchargeant le fichier soit en collant le contenu à partir de votre presse-papiers.


endif::gcp[]

ifdef::aws[]

. *Amazon Web Services* : fournissez les informations d'identification utilisateur Amazon Web Services IAM en téléchargeant le fichier ou en collant le contenu à partir de votre presse-papiers.


endif::aws[]

. Sélectionnez *Ajouter des informations d'identification*.


Vous pouvez maintenant sélectionner les informations d'identification lorsque vous ajoutez un cluster à Astra Control.



== Supprimer les informations d'identification

Supprimez les informations d'identification d'un compte à tout moment. Vous ne devez supprimer les informations d'identification qu'après link:unmanage.html["annuler la gestion de tous les clusters"], sauf si vous faites pivoter des informations d'identification (voir  credentials).


NOTE: Le premier ensemble d'informations d'identification que vous ajoutez à Astra Control est toujours utilisé car Astra Control utilise les informations d'identification pour s'authentifier auprès du compartiment de secours. Il est préférable de ne pas supprimer ces informations d'identification.

.Étapes
. Sélectionnez *compte > informations d'identification*.
. Sélectionnez la liste déroulante dans la colonne *État* pour les informations d'identification que vous souhaitez supprimer.
. Sélectionnez *Supprimer*.
. Saisissez le nom des informations d'identification pour confirmer la suppression, puis sélectionnez *Oui, Supprimer les informations d'identification*.


Astra Control supprime les informations d'identification du compte.



== Faire pivoter les informations d'identification

Vous pouvez faire pivoter les informations d'identification de votre compte. Si vous faites pivoter les informations d'identification, faites-les pivoter pendant une fenêtre de maintenance lorsqu'aucune sauvegarde n'est en cours (planifiée ou à la demande).

.Étapes
. Supprimez les informations d'identification existantes en suivant les étapes de la section  credentials.
. Ajoutez les nouvelles informations d'identification en suivant les étapes de la section  credentials.
. Mettez à jour toutes les rubriques pour utiliser les nouvelles informations d'identification :
+
.. Sous *gérer votre stockage*, sélectionnez *seaux*.
.. Sélectionnez la liste déroulante dans la colonne *actions* pour le compartiment que vous souhaitez modifier.
.. Sélectionnez *Modifier*.
.. Dans la section *Sélectionner les informations d'identification*, choisissez les nouvelles informations d'identification que vous avez ajoutées à Astra Control.
.. Sélectionnez *mettre à jour*.
.. Répétez les étapes *b* à *e* pour les compartiments restants de votre système.




Astra Control commence à utiliser les nouveaux identifiants du fournisseur cloud.
