---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: bucket, buckets, add buckets, change default bucket, default, default bucket, remove bucket, delete bucket, S3, s3, storage, object storage, object store, store, object 
summary: Gérez les compartiments utilisés par Astra pour les sauvegardes et les clones en ajoutant des compartiments supplémentaires et en changeant le compartiment par défaut pour les clusters de votre fournisseur de cloud. 
---
= Gestion des compartiments
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Vous pouvez gérer les compartiments qu'Astra utilise pour la sauvegarde et le clonage. Vous pouvez ajouter des compartiments supplémentaires, supprimer des compartiments existants et modifier le compartiment par défaut des clusters Kubernetes dans une instance cloud.

Seuls les propriétaires et les administrateurs peuvent gérer les compartiments.



== Utilisation des seaux par Astra Control

Lorsque vous commencez à gérer votre premier cluster Kubernetes pour une instance cloud, Astra Control Service crée le compartiment initial pour cette instance link:manage-cloud-instances.html["instance cloud"^].

Vous pouvez désigner manuellement un compartiment comme compartiment par défaut pour une instance cloud. Dans ce cas, Astra Control Service utilise ce compartiment par défaut pour les sauvegardes et les clones que vous créez sur n'importe quel cluster géré de cette instance cloud (vous pouvez sélectionner un compartiment différent pour les sauvegardes). Si vous effectuez un clone dynamique d'une application depuis l'un des clusters gérés d'une instance cloud vers un autre cluster, Astra Control Service utilise le compartiment par défaut de l'instance cloud source pour effectuer l'opération de clonage.

Vous pouvez définir le même compartiment que le compartiment par défaut pour plusieurs instances cloud.

Vous pouvez faire votre choix parmi les compartiments lorsque vous créez une stratégie de protection ou que vous démarrez une sauvegarde ad hoc.


TIP: Le service de contrôle Astra vérifie si un compartiment de destination est accessible avant de démarrer une sauvegarde ou un clone.



== Afficher les compartiments existants

Affichez la liste des compartiments disponibles pour Astra Control Service pour déterminer leur état et identifier le compartiment par défaut (si défini) de votre instance cloud.

Un godet peut avoir l'un des États suivants :

En attente:: Une fois que vous avez ajouté un compartiment, celui-ci commence à l'état en attente tandis qu'Astra Control le découvre.
Disponibilité:: Le godet peut être utilisé par Astra Control.
Supprimé:: Le godet n'est pas opérationnel actuellement. Passez votre souris sur l'icône d'état pour identifier le problème.
+
--
Si un compartiment est retiré, vous pouvez toujours le définir comme compartiment par défaut et l'affecter à une planification de protection. Mais si le compartiment n'est pas disponible au moment où une opération de protection des données démarre, cette opération échoue.

--


.Étape
. Aller à *seaux*.
+
La liste des compartiments disponibles pour Astra Control Service s'affiche.





== Ajouter un godet supplémentaire

Vous pouvez ajouter des compartiments supplémentaires à tout moment. Vous avez ainsi le choix entre compartiments lors de la création d'une règle de protection ou du démarrage d'une sauvegarde ad hoc. Vous pouvez également modifier le compartiment par défaut utilisé par une instance cloud.

Vous pouvez ajouter les types de compartiments suivants :

* Amazon Web Services
* S3 générique
* Google Cloud Platform
* Microsoft Azure
* NetApp ONTAP S3
* NetApp StorageGRID S3


.Avant de commencer
* Assurez-vous de connaître le nom d'un compartiment existant.
* Assurez-vous d'avoir des identifiants pour le compartiment qui fournissent à Astra Control les autorisations dont il a besoin pour gérer le compartiment.


ifdef::azure[]

* Si votre compartiment est dans Microsoft Azure :
+
** Le compartiment doit appartenir au groupe de ressources nommé _astra-backup-rg_.
** Si le paramètre de performance de l'instance de compte de stockage Azure est défini sur « Premium », le paramètre « Type de compte Premium » doit être défini sur « blobs de bloc ».




endif::azure[]

.Étapes
. Aller à *seaux*.
. Sélectionnez *Ajouter* et suivez les invites pour ajouter le compartiment.
+
** *Type* : Choisissez votre fournisseur cloud.
** *Nom de compartiment existant* : saisissez le nom du compartiment.
** *Description* : saisissez éventuellement une description du godet.




ifdef::azure[]

* *Compte de stockage* (Azure uniquement) : saisissez le nom de votre compte de stockage Azure. Ce compartiment doit appartenir au groupe de ressources nommé _astra-backup-rg_.


endif::azure[]

ifdef::aws[]

* *Nom du serveur S3 ou adresse IP* (types de compartiment AWS et S3 uniquement) : entrez le nom de domaine complet du terminal S3 correspondant à votre région, sans `https://`. Reportez-vous à la section https://docs.aws.amazon.com/general/latest/gr/s3.html["La documentation Amazon"^] pour en savoir plus.


endif::aws[]

* *Sélectionner les informations d'identification* : entrez les informations d'identification qui fournissent à Astra Control Service les autorisations dont il a besoin pour gérer le compartiment. Les informations à fournir varient en fonction du type de godet.
+
.. Sélectionnez *Ajouter* pour ajouter le compartiment.




.Résultat
ASTRA Control Service ajoute le compartiment. Vous pouvez désormais choisir ce compartiment lors de la création d'une règle de protection ou de l'exécution d'une sauvegarde ad hoc. Vous pouvez également définir ce compartiment comme compartiment par défaut pour une instance cloud.



== Modifier le compartiment par défaut

Vous pouvez modifier le compartiment par défaut d'une instance cloud. ASTRA Control Service utilisera ce compartiment par défaut pour les sauvegardes et les clones. Chaque instance cloud dispose de son propre compartiment par défaut.


NOTE: Astra Control n'attribue pas automatiquement de compartiment par défaut à une instance de cloud. Vous devez définir manuellement un compartiment par défaut pour une instance de cloud avant d'effectuer des opérations de clonage d'applications entre deux clusters.

.Étapes
. Accédez à *Cloud instances*.
. Sélectionnez le menu de configuration dans la colonne *actions* pour l'instance de Cloud que vous souhaitez modifier.
. Sélectionnez *Modifier*.
. Dans la liste des compartiments, sélectionnez le compartiment par défaut pour cette instance cloud.
. Sélectionnez *mettre à jour*.




== Déposer un godet

Il est possible de retirer un godet qui n'est plus utilisé ou qui n'est pas en bon état. Pour simplifier et à jour la configuration du magasin d'objets,

[NOTE]
====
* Vous ne pouvez pas supprimer un compartiment par défaut. Si vous souhaitez retirer ce compartiment, sélectionnez tout d'abord un autre compartiment comme valeur par défaut.
* Vous ne pouvez pas supprimer un compartiment WORM (Write Once, Read Many) avant l'expiration de la période de conservation du fournisseur cloud du compartiment. Les godets À VIS SANS FIN sont signalés par « verrouillé » à côté du nom du compartiment.


====
.Avant de commencer
* Avant de commencer, assurez-vous qu'aucune sauvegarde n'est en cours d'exécution ou terminée pour ce compartiment.
* Vérifiez que le compartiment n'est pas utilisé pour les sauvegardes planifiées.


Si c'est le cas, vous ne pourrez pas continuer.

.Étapes
. Aller à *seaux*.
. Dans le menu *actions*, sélectionnez *Supprimer*.
+

NOTE: Astra Control veille à l'absence de règles de planification qui utilise le compartiment pour les sauvegardes et à l'absence de sauvegardes actives dans le compartiment.

. Tapez « Supprimer » pour confirmer l'action.
. Sélectionnez *Oui, retirez le godet*.




== [Aperçu technique] Gérez un compartiment à l'aide d'une ressource personnalisée

Vous pouvez ajouter un compartiment à l'aide d'une ressource personnalisée Astra Control (CR) sur le cluster d'applications. Il est essentiel d'ajouter des fournisseurs de compartiments de stockage objet pour sauvegarder les applications et le stockage persistant ou pour cloner les applications entre les clusters. Astra Control stocke les sauvegardes ou les clones dans les compartiments de magasin d'objets que vous définissez. Si vous utilisez la méthode de ressources personnalisées, la fonctionnalité de snapshots d'applications requiert un compartiment.

Si vous clonez la configuration de vos applications et le stockage persistant vers le même cluster, il n'est pas nécessaire d'utiliser un compartiment dans Astra Control.

La ressource personnalisée du compartiment pour Astra Control est appelée AppVault. Ce CR contient les configurations nécessaires à l'utilisation d'un godet dans les opérations de protection.

.Avant de commencer
* Assurez-vous que vous disposez d'un compartiment accessible depuis vos clusters gérés par Astra Control Center.
* Vérifiez que vous disposez des informations d'identification pour le compartiment.
* S'assurer que le godet est de l'un des types suivants :
+
** NetApp ONTAP S3
** NetApp StorageGRID S3
** Microsoft Azure
** S3 générique





NOTE: Amazon Web Services (AWS) et Google Cloud Platform (GCP) utilisent le type de compartiment S3 générique.


NOTE: Bien qu'Astra Control Center prenne en charge Amazon S3 en tant que fournisseur de compartiments génériques, Astra Control Center peut ne pas prendre en charge tous les fournisseurs de magasins d'objets qui affirment la prise en charge d'Amazon S3.

.Étapes
. Créer le fichier de ressource personnalisée (CR) et le nommer (par exemple, `astra-appvault.yaml`).
. Configurez les attributs suivants :
+
** *metadata.name*: _(obligatoire)_ le nom de la ressource personnalisée AppVault.
** *Spec.prefix*: _(Facultatif)_ chemin précédé des noms de toutes les entités stockées dans le AppVault.
** *spec.providerConfig*: _(obligatoire)_ stocke la configuration nécessaire pour accéder à AppVault à l'aide du fournisseur spécifié.
** *spec.providerCredentials*: _(obligatoire)_ stocke les références à toute information d'identification requise pour accéder à AppVault à l'aide du fournisseur spécifié.
+
*** *spec.providerCredentials.valueFromSecret*: _(Facultatif)_ indique que la valeur d'identification doit provenir d'un secret.
+
**** *Key*: _(requis si valueFromSecret est utilisé)_ la clé valide du secret à sélectionner.
**** *Nom*: _(requis si valueFromSecret est utilisé)_ Nom du secret contenant la valeur de ce champ. Doit être dans le même espace de noms.




** *spec.providerType*: _(obligatoire)_ détermine ce qui fournit la sauvegarde, par exemple, NetApp ONTAP S3 ou Microsoft Azure.
+
Exemple YAML :

+
[source, yaml]
----
apiVersion: astra.netapp.io/v1
kind: AppVault
metadata:
  name: astra-appvault
spec:
  providerType: generic-s3
  providerConfig:
    path: testpath
    endpoint: 192.168.1.100:80
    bucketName: bucket1
    secure: "false"
  providerCredentials:
    accessKeyID:
      valueFromSecret:
        name: s3-creds
        key: accessKeyID
    secretAccessKey:
      valueFromSecret:
        name: s3-creds
        key: secretAccessKey
----


. Après avoir renseigné le `astra-appvault.yaml` Fichier avec les valeurs correctes, appliquer la CR :
+
[source, console]
----
kubectl apply -f astra-appvault.yaml -n astra-connector
----
+

NOTE: Lorsque vous ajoutez un godet, Astra Control marque un godet avec l'indicateur de compartiment par défaut. Le premier compartiment que vous créez devient le compartiment par défaut. Au fur et à mesure que vous ajoutez des compartiments, vous pourrez décider plus tard link:../use/manage-buckets.html#set-the-default-bucket["définir un autre compartiment par défaut"^].





== Trouvez plus d'informations

* https://docs.netapp.com/us-en/astra-automation/index.html["Utilisez l'API de contrôle Astra"^]

