---
sidebar: sidebar 
permalink: use/monitor-running-tasks.html 
keywords: activity, log, activities, running, tasks, monitor, status, state 
summary: 'Vous pouvez afficher des détails sur l"exécution des tâches dans Astra Control. Par exemple, lorsque vous effectuez un snapshot, une sauvegarde ou un clone.' 
---
= Surveillez les tâches en cours d'exécution
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Vous pouvez afficher des détails sur l'exécution des tâches et des tâches qui ont terminé, échoué ou ont été annulées au cours des 24 dernières heures dans Astra Control. Par exemple, vous pouvez afficher l'état d'une opération de sauvegarde, de restauration ou de clonage. Pour plus d'informations, reportez-vous aux pourcentages terminés et au temps restant estimé. Vous pouvez afficher l'état d'une opération planifiée exécutée ou d'une opération que vous avez démarrée manuellement.

Lors de l'affichage d'une tâche en cours d'exécution ou terminée, vous pouvez développer les détails de la tâche pour afficher l'état de chacune des sous-tâches. La barre de progression de la tâche est verte pour les tâches en cours ou terminées, bleue pour les tâches annulées et rouge pour les tâches ayant échoué en raison d'une erreur.


NOTE: Pour les opérations de clonage, les sous-tâches se composent d'un snapshot et d'une opération de restauration de snapshot.

Pour plus d'informations sur les tâches ayant échoué, reportez-vous à la section link:monitor-account-activity.html["Surveillez l'activité des comptes"].

.Étapes
. Pendant qu'une tâche est en cours d'exécution, accédez à *applications*.
. Sélectionnez le nom d'une application dans la liste.
. Dans les détails de l'application, sélectionnez l'onglet *tâches*.
+
Vous pouvez afficher les détails des tâches actuelles ou passées et filtrer par état de tâche.




NOTE: Les tâches sont conservées dans la liste *tâches* pour un maximum de 24 heures. Vous pouvez configurer cette limite et d'autres paramètres du moniteur de tâches à l'aide de l' https://["API de contrôle Astra"^].
