---
sidebar: sidebar 
permalink: use/restore-apps.html 
keywords: restore app, restoring an app, restore an app, restore, ontap-nas-economy, disruptive, migration 
summary: 'Astra Control permet de restaurer la configuration de vos applications et le stockage persistant à partir d"un snapshot ou d"une sauvegarde. Les sauvegardes de stockage persistant sont transférées à partir de votre magasin d"objets, de sorte qu"une restauration à partir d"une sauvegarde existante se fera le plus rapidement possible.' 
---
= Restaurez les applications
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control peut restaurer votre application à partir d'un snapshot ou d'une sauvegarde. La restauration d'un snapshot existant est plus rapide lors de la restauration d'une application sur le même cluster. Vous pouvez utiliser l'interface utilisateur de contrôle Astra ou https://docs.netapp.com/us-en/astra-automation/index.html["API de contrôle Astra"^] pour restaurer des applications.


NOTE: Si vous ajoutez un filtre d'espace de noms à un crochet d'exécution qui s'exécute après une opération de restauration ou de clonage et que la source et la destination de restauration ou de clonage sont dans des espaces de noms différents, le filtre d'espace de noms est appliqué uniquement à l'espace de noms de destination.

.Avant de commencer
* *Protéger vos applications en premier* : il est fortement recommandé de prendre un instantané ou une sauvegarde de votre application avant de la restaurer. Vous pourrez ainsi cloner à partir de l'instantané ou de la sauvegarde si la restauration échoue.
* *Vérifier les volumes de destination* : si vous restaurez vers une classe de stockage différente, assurez-vous que la classe de stockage utilise le même mode d'accès au volume persistant (par exemple, ReadWriteMaly). L'opération de restauration échoue si le mode d'accès au volume persistant de destination est différent. Par exemple, si votre volume persistant source utilise le mode d'accès RWX, en sélectionnant une classe de stockage de destination qui ne peut pas fournir RWX, comme les disques gérés Azure, AWS EBS, Google persistent Disk ou `ontap-san`, provoque l'échec de l'opération de restauration. Pour plus d'informations sur les modes d'accès aux volumes persistants, reportez-vous au https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes["Kubernetes"^] documentation :
* *Planifier les besoins en espace* : lorsque vous effectuez une restauration sur place d'une application utilisant un stockage NetApp ONTAP, l'espace utilisé par l'application restaurée peut doubler. Une fois la restauration sur place effectuée, supprimez les snapshots indésirables de l'application restaurée pour libérer de l'espace de stockage.
* *Pilotes de classe de stockage pris en charge* : Astra Control prend en charge la restauration des sauvegardes à l'aide de classes de stockage soutenues par les pilotes suivants :
+
** `ontap-nas`
** `ontap-nas-economy`
** `ontap-san`
** `ontap-san-economy`


* * (Pilote ontap-nas-Economy uniquement) sauvegardes et restaurations* : avant de sauvegarder ou de restaurer une application qui utilise une classe de stockage sauvegardée par `ontap-nas-economy` pilote, vérifiez que link:../use/protect-apps.html#enable-backup-and-restore-for-ontap-nas-economy-operations["Le répertoire Snapshot du système back-end de stockage ONTAP est masqué"]. Si ce répertoire n'est pas masqué, l'accès à votre application risque d'être perdu, en particulier s'il utilise NFSv3.


[CAUTION]
====
L'exécution d'une opération de restauration sur place sur une application qui partage des ressources avec une autre application peut avoir des résultats inattendus. Toutes les ressources partagées entre les applications sont remplacées lorsqu'une restauration sur place est effectuée sur l'une des applications.

====
.Étapes
. Sélectionnez *applications*, puis le nom d'une application.
. Dans le menu Options de la colonne actions, sélectionnez *Restaurer*.
. Choisissez le type de restauration :
+
** *Restaurer les espaces de noms d'origine* : utilisez cette procédure pour restaurer l'app sur place dans le cluster d'origine.
+
... Sélectionnez le snapshot ou la sauvegarde à utiliser pour restaurer l'application sur place, ce qui restaure l'application à une version antérieure de elle-même.
... Sélectionnez *Suivant*.
+

NOTE: Si vous restaurez vers un espace de nom qui a déjà été supprimé, un nouvel espace de nom avec le même nom est créé dans le cadre du processus de restauration. Tous les utilisateurs disposant des droits de gestion des applications dans l'espace de noms précédemment supprimé doivent restaurer manuellement les droits sur l'espace de noms nouvellement créé.



** *Restaurer vers de nouveaux espaces de noms* : utilisez cette procédure pour restaurer l'application vers un autre cluster ou avec des espaces de noms différents de la source. Vous pouvez également utiliser cette procédure pour migrer une application vers une autre classe de stockage.
+
... Spécifiez le nom de l'application restaurée.
... Choisissez le cluster de destination pour l'application que vous souhaitez restaurer.
... Entrez un espace de noms de destination pour chaque espace de noms source associé à l'application.
+

NOTE: Astra Control crée de nouveaux espaces de noms de destination dans le cadre de cette option de restauration. Les espaces de noms de destination que vous spécifiez ne doivent pas être déjà présents sur le cluster de destination.

... Sélectionnez *Suivant*.
... Sélectionnez le snapshot ou la sauvegarde à utiliser pour restaurer l'application.
... Sélectionnez *Suivant*.
... Options au choix :
+
**** *Restaurer à l'aide des classes de stockage d'origine* : l'application utilise la classe de stockage associée à l'origine, sauf si elle n'existe pas sur le cluster cible. Dans ce cas, la classe de stockage par défaut du cluster sera utilisée.
**** *Restaurer à l'aide d'une classe de stockage différente* : sélectionnez une classe de stockage qui existe sur le cluster cible. Tous les volumes d'application, quelles que soient les classes de stockage qui leur sont associées à l'origine, seront migrés vers cette classe de stockage différente dans le cadre de la restauration.


... Sélectionnez *Suivant*.




. Sélectionnez les ressources à filtrer :
+
** *Restaurer toutes les ressources* : restaurez toutes les ressources associées à l'application d'origine.
** *Filtrer les ressources* : spécifiez des règles pour restaurer un sous-ensemble des ressources d'application d'origine :
+
... Choisissez d'inclure ou d'exclure des ressources de l'application restaurée.
... Sélectionnez *Ajouter une règle d'inclusion* ou *Ajouter une règle d'exclusion* et configurez la règle pour filtrer les ressources appropriées lors de la restauration de l'application. Vous pouvez modifier une règle ou la supprimer et créer une nouvelle règle jusqu'à ce que la configuration soit correcte.
+

NOTE: Pour en savoir plus sur la configuration des règles d'inclusion et d'exclusion, reportez-vous à la section <<Filtrer les ressources pendant la restauration d'une application>>.





. Sélectionnez *Suivant*.
. Examinez attentivement les détails de l'action de restauration, tapez "restore" (si vous y êtes invité) et sélectionnez *Restore*.


.Résultat
Astra Control restaure l'application en fonction des informations que vous avez fournies. Si vous avez restauré l'application sur place, le contenu des volumes persistants existants est remplacé par le contenu des volumes persistants de l'application restaurée.


NOTE: Après une opération de protection des données (clonage, sauvegarde ou restauration) et après le redimensionnement du volume persistant, la nouvelle taille du volume s'affiche dans l'interface utilisateur Web pendant vingt minutes. La protection des données fonctionne avec succès en quelques minutes et vous pouvez utiliser le logiciel de gestion pour le système back-end pour confirmer la modification de la taille du volume.


NOTE: Tout utilisateur membre aux contraintes de namespace par nom/ID d'espace de noms ou par libellés de namespace peut cloner ou restaurer une application vers un nouvel espace de noms sur le même cluster ou vers tout autre cluster du compte de son entreprise. Cependant, le même utilisateur ne peut pas accéder à l'application clonée ou restaurée dans le nouvel espace de noms. Après qu'une opération de clonage ou de restauration a créé un nouvel espace de noms, l'administrateur/propriétaire du compte peut modifier le compte utilisateur membre et mettre à jour les contraintes de rôle pour que l'utilisateur affecté accorde l'accès au nouvel espace de noms.



== Filtrer les ressources pendant la restauration d'une application

Vous pouvez ajouter une règle de filtre à un link:../use/restore-apps.html["restaurer"] opération qui spécifie les ressources d'application existantes à inclure ou à exclure de l'application restaurée. Vous pouvez inclure ou exclure des ressources en fonction d'un espace de noms, d'un libellé ou d'un GVK (GroupVersionKind) spécifié.

.En savoir plus sur les scénarios d'inclusion et d'exclusion
[%collapsible]
====
* *Vous sélectionnez une règle d'inclusion avec des espaces de noms d'origine (restauration sur place)* : les ressources d'application existantes que vous définissez dans la règle seront supprimées et remplacées par celles de l'instantané ou de la sauvegarde sélectionné que vous utilisez pour la restauration. Toutes les ressources que vous ne spécifiez pas dans la règle inclure resteront inchangées.
* *Vous sélectionnez une règle d'inclusion avec de nouveaux espaces de noms* : utilisez la règle pour sélectionner les ressources spécifiques que vous voulez dans l'application restaurée. Les ressources que vous ne spécifiez pas dans la règle d'inclusion ne seront pas incluses dans l'application restaurée.
* *Vous sélectionnez une règle d'exclusion avec les espaces de noms d'origine (restauration sur place)* : les ressources que vous spécifiez pour être exclues ne seront pas restaurées et resteront inchangées. Les ressources que vous ne spécifiez pas pour exclure seront restaurées à partir de l'instantané ou de la sauvegarde. Toutes les données des volumes persistants seront supprimées et recréées si l'état correspondant fait partie des ressources filtrées.
* *Vous sélectionnez une règle d’exclusion avec de nouveaux espaces de noms* : utilisez la règle pour sélectionner les ressources spécifiques que vous souhaitez supprimer de l’application restaurée. Les ressources que vous ne spécifiez pas pour exclure seront restaurées à partir de l'instantané ou de la sauvegarde.


====
Les règles sont des types d'inclusion ou d'exclusion. Les règles combinant l'inclusion et l'exclusion des ressources ne sont pas disponibles.

.Étapes
. Après avoir choisi de filtrer les ressources et sélectionné une option d'inclusion ou d'exclusion dans l'assistant Restaurer l'application, sélectionnez *Ajouter une règle d'inclusion* ou *Ajouter une règle d'exclusion*.
+

NOTE: Vous ne pouvez pas exclure des ressources dont la portée est définie par le cluster qui sont automatiquement incluses dans Astra Control.

. Configurez la règle de filtre :
+

NOTE: Vous devez spécifier au moins un espace de noms, un libellé ou un GVK. Assurez-vous que toutes les ressources que vous conservez après l'application des règles de filtre sont suffisantes pour que l'application restaurée reste en bon état.

+
.. Sélectionnez un espace de noms spécifique pour la règle. Si vous ne faites pas de sélection, tous les espaces de noms seront utilisés dans le filtre.
+

NOTE: Si votre application contenait initialement plusieurs espaces de noms et que vous les restaurez à de nouveaux espaces de noms, tous les espaces de noms seront créés même s'ils ne contiennent pas de ressources.

.. (Facultatif) Entrez un nom de ressource.
.. (Facultatif) *Sélecteur d'étiquettes* : inclure un https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors["sélecteur d'étiquettes"^] pour ajouter à la règle. Le sélecteur d'étiquettes est utilisé pour filtrer uniquement les ressources correspondant à l'étiquette sélectionnée.
.. (Facultatif) sélectionnez *utiliser GVK (GroupVersionKind) défini pour filtrer les ressources* pour des options de filtrage supplémentaires.
+

NOTE: Si vous utilisez un filtre GVK, vous devez spécifier la version et le type.

+
... (Facultatif) *Group* : dans la liste déroulante, sélectionnez le groupe API Kubernetes.
... *Type* : dans la liste déroulante, sélectionnez le schéma d'objet du type de ressource Kubernetes à utiliser dans le filtre.
... *Version* : sélectionnez la version de l'API Kubernetes.




. Vérifiez la règle créée en fonction de vos entrées.
. Sélectionnez *Ajouter*.
+

TIP: Vous pouvez créer autant de règles d'inclusion et d'exclusion de ressources que vous le souhaitez. Les règles apparaissent dans le résumé de l'application de restauration avant de lancer l'opération.


