---
sidebar: sidebar 
permalink: use/unmanage.html 
keywords: unmanage app, remove app, stop managing app, stop managing clusters, unmanage cluster, remove cluster 
summary: 'Supprimez toutes les applications ou clusters que vous ne souhaitez plus gérer d"Astra Control.' 
---
= Annuler la gestion des applications et des clusters
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Supprimez toutes les applications ou clusters que vous ne souhaitez plus gérer d'Astra Control.



== Arrêtez la gestion d'une application

Arrêtez de gérer les applications que vous ne souhaitez plus sauvegarder, créer des copies Snapshot ou cloner à partir d'Astra Control.

Lorsque vous annulez la gestion d'une application :

* Toutes les sauvegardes et tous les instantanés existants seront supprimés.
* Les applications et les données restent disponibles.


.Étapes
. Dans la barre de navigation de gauche, sélectionnez *applications*.
. Sélectionnez l'application.
. Dans le menu Options de la colonne actions, sélectionnez *Unmanage*.
. Vérifiez les informations.
. Tapez « Unmanage » pour confirmer.
. Sélectionnez *Oui, Annuler la gestion de l'application*.


.Résultat
Astra Control cesse de gérer l'application.



== Arrêtez la gestion d'un cluster

Arrêtez de gérer le cluster que vous ne souhaitez plus gérer avec Astra Control.

ifdef::gcp[]


NOTE: Avant d'annuler la gestion du cluster, vous devez annuler la gestion des applications associées au cluster.

Il est recommandé de supprimer le cluster d'Astra Control avant de le supprimer via GCP.

endif::gcp[]

Lorsque vous dégérez un cluster :

* Cette action empêche la gestion de votre cluster par Astra Control. Elle ne modifie pas la configuration du cluster et ne supprime pas le cluster.
* ASTRA Control Provisioner ou Astra Trident ne seront pas désinstallés du cluster. https://docs.netapp.com/us-en/trident/trident-managing-k8s/uninstall-trident.html["Découvrez comment désinstaller Astra Trident"^].


.Étapes
. Sélectionnez *clusters*.
. Cochez la case correspondant au cluster que vous ne souhaitez plus gérer.
. Dans le menu Options de la colonne *actions*, sélectionnez *ne pas gérer*.
. Confirmez que vous souhaitez annuler la gestion du cluster, puis sélectionnez *Oui, dégérer*.


.Résultat
L'état du cluster devient *Suppression*. Ensuite, le cluster sera supprimé de la page *clusters* et il n'est plus géré par Astra Control.



== Suppression de clusters de votre fournisseur de cloud

Avant de supprimer un cluster Kubernetes contenant des volumes persistants (PV) résidant sur des classes de stockage NetApp, vous devez d'abord supprimer les demandes de volume persistant suivant l'une des méthodes ci-dessous. La suppression de la demande de volume persistant et du volume persistant avant la suppression du cluster évite de recevoir des factures inattendues de votre fournisseur cloud.

* *Méthode #1* : supprimez les espaces de noms de charge de travail de l'application du cluster. Do _not_ delete l'espace de noms Trident.
* *Méthode #2* : supprimez les demandes de volume persistant et les modules, ou le déploiement où les volumes persistants sont montés.


Lorsque vous gérez un cluster Kubernetes à partir d'Astra Control, les applications qui ce cluster utilisent votre fournisseur cloud comme back-end de stockage pour les volumes persistants. Si vous supprimez le cluster de votre fournisseur cloud sans supprimer au préalable les volumes persistants, les volumes back-end sont _non_ supprimés avec le cluster.

L'utilisation de l'une des méthodes ci-dessus supprimera le PVS correspondant de votre cluster. Assurez-vous qu'aucun volume persistant ne réside dans les classes de stockage NetApp du cluster avant de les supprimer.

Si vous n'avez pas supprimé les volumes persistants avant la suppression du cluster, vous devrez supprimer manuellement les volumes back-end de votre fournisseur de cloud.
