---
sidebar: sidebar 
permalink: use/view-clusters.html 
keywords: view cluster, cluster storage, cluster overview 
summary: Une fois que vous avez ajouté des clusters Kubernetes à Astra Control, vous pouvez afficher des informations détaillées sur le cluster, notamment son emplacement, les nœuds de travail, les volumes persistants et les classes de stockage. 
---
= Afficher l'état de santé et les détails des clusters
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Une fois que vous avez ajouté des clusters Kubernetes à Astra Control, vous pouvez afficher des informations détaillées sur le cluster, notamment son emplacement, les nœuds de travail, les volumes persistants et les classes de stockage.

.Étapes
. Dans l'interface utilisateur du service de contrôle Astra, sélectionnez *clusters*.
. Sur la page *clusters*, sélectionnez le cluster dont vous souhaitez afficher les détails.
+

NOTE: Si un cluster se trouve dans le `removed` État et pourtant, la connectivité cluster et réseau semble saine (les tentatives externes d'accès au cluster via les API Kubernetes sont réussies). Le kubeconfig que vous avez fourni au contrôle Astra pourrait ne plus être valide. Cela peut être dû à une rotation ou à une expiration du certificat sur le cluster. Pour corriger ce problème, mettez à jour les informations d'identification associées au cluster dans Astra Control à l'aide du link:https://docs.netapp.com/us-en/astra-automation/index.html["API de contrôle Astra"].

. Consultez les informations sur les onglets *Présentation*, *stockage* et *activité* pour trouver les informations que vous recherchez.
+
** *Présentation* : détails sur les nœuds de travail, y compris leur état.
** *Stockage* : volumes persistants associés au calcul, y compris la classe et l'état du stockage.
** *Activité* : activités liées au cluster.





NOTE: Vous pouvez également afficher les informations du groupe d'instruments à partir du service de contrôle Astra *Tableau de bord*. Dans l'onglet *clusters* sous *Résumé des ressources*, vous pouvez sélectionner les clusters gérés, qui vous permettent d'accéder à la page *clusters*. Après avoir accédé à la page *clusters*, suivez les étapes décrites ci-dessus.
