---
sidebar: sidebar 
permalink: get-started/add-private-self-managed-cluster.html 
keywords: discover cluster, add cluster, add kubernetes cluster, discover kubernetes cluster, add cluster 
summary: 'Une fois votre environnement configuré, vous êtes prêt à créer un cluster Kubernetes, puis à l"ajouter à Astra Control Service.' 
---
= Ajoutez un cluster privé autogéré à Astra Control Service
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Une fois votre environnement configuré, vous êtes prêt à créer un cluster Kubernetes, puis à l'ajouter à Astra Control Service.

Un cluster autogéré est un cluster que vous provisionnez et gérez directement. ASTRA Control Service prend en charge les clusters autogérés qui s'exécutent dans un environnement de cloud public. Vous pouvez ajouter un cluster auto-géré au service Astra Control en téléchargeant un `kubeconfig.yaml` fichier. Vous devez vous assurer que le cluster répond aux exigences décrites ici.



== Distributions Kubernetes prises en charge

Vous pouvez utiliser Astra Control Service pour gérer les types suivants de clusters privés et autogérés :

[cols="2*"]
|===
| Distribution Kubernetes | Versions prises en charge 


| Kubernetes (en amont) | 1.26 à 1.28 


| Rancher Kubernetes Engine (RKE) | RKE 1.3 avec Rancher Manager 2.6
RKE 1.4 avec Rancher Manager 2.7
RKE 2 (v1.24.x) avec Rancher 2.6
RKE 2 (v1.26.x) avec Rancher 2.7 


| Plateforme de conteneurs Red Hat OpenShift | 4.11 à 4.14 
|===
Ces instructions supposent que vous avez déjà créé un cluster privé et préparé une méthode sécurisée pour y accéder à distance.

Pour ajouter votre cluster privé à Astra Control Service, vous devez effectuer les tâches suivantes :

. <<Poser le connecteur Astra>>
. <<Configuration du stockage persistant>>
. <<Ajoutez le cluster privé autogéré à Astra Control Service>>




== Poser le connecteur Astra

Avant d'ajouter un cluster privé, vous devez installer Astra Connector sur le cluster afin qu'Astra Control puisse communiquer avec lui. Reportez-vous à la section link:install-astra-connector.html["Installez Astra Connector pour les clusters privés"] pour obtenir des instructions.



== Configuration du stockage persistant

Configurer le stockage persistant pour le cluster. Pour plus d'informations sur la configuration du stockage persistant, reportez-vous à la documentation de mise en route :

ifdef::azure[]

* link:set-up-microsoft-azure-with-anf.html["Configuration de Microsoft Azure avec Azure NetApp Files"^]
* link:set-up-microsoft-azure-with-amd.html["Configuration de Microsoft Azure avec des disques gérés Azure"^]


endif::azure[]

ifdef::aws[]

* link:set-up-amazon-web-services.html["Configurer Amazon Web Services"^]


endif::aws[]

ifdef::gcp[]

* link:set-up-google-cloud.html["Configurez Google Cloud"^]


endif::gcp[]



== Ajoutez le cluster privé autogéré à Astra Control Service

Vous pouvez maintenant ajouter le cluster privé à Astra Control Service.

.Avant de commencer
[%collapsible%open]
====
Un cluster autogéré est un cluster que vous provisionnez et gérez directement. ASTRA Control Service prend en charge les clusters autogérés qui s'exécutent dans un environnement de cloud public. Vos clusters autogérés peuvent utiliser Astra Trident pour s'interfacer avec les services de stockage NetApp ou les pilotes Container Storage interface (CSI) pour s'interfacer avec Amazon Elastic Block Store (EBS), les disques gérés Azure et le service Google persistent Disk.

ASTRA Control Service prend en charge les clusters autogérés qui utilisent les distributions Kubernetes suivantes :

* Plateforme de conteneurs Red Hat OpenShift
* Moteur rancher Kubernetes
* Kubernetes en amont


Votre cluster autogéré doit répondre aux exigences suivantes :

* Le cluster doit être accessible via Internet.
* Si vous utilisez ou prévoyez d'utiliser le stockage activé avec des pilotes CSI, les pilotes CSI appropriés doivent être installés sur le cluster. Pour plus d'informations sur l'utilisation des pilotes CSI pour intégrer le stockage, reportez-vous à la documentation de votre service de stockage.
* Vous avez accès au fichier kubeconfig du cluster qui ne contient qu'un seul élément de contexte. Suivre link:create-kubeconfig.html["ces instructions"^] pour générer un fichier kubeconfig.
* Si vous ajoutez le cluster à l'aide d'un fichier kubeconfig qui fait référence à une autorité de certification privée (CA), ajoutez la ligne suivante au `cluster` section du fichier kubeconfig. Cela permet à Astra Control d'ajouter le cluster :
+
[listing]
----
insecure-skip-tls-verify: true
----
* *Rancher uniquement*: Lorsque vous gérez des clusters d'applications dans un environnement Rancher, modifiez le contexte par défaut du cluster d'applications dans le fichier kubeconfig fourni par Rancher pour utiliser un contexte de plan de contrôle au lieu du contexte du serveur d'API Rancher. La charge est réduite sur le serveur API Rancher et les performances sont améliorées.
* *Astra Trident* : si vous utilisez ou prévoyez d'utiliser le stockage NetApp, assurez-vous d'avoir installé la dernière version d'Astra Trident. Si Astra Trident est déjà installé, link:check-astra-trident-version.html["vérifiez qu'il s'agit de la dernière version"^].
+

NOTE: C'est possible https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html#choose-the-deployment-method["Déployez Astra Trident"^] Utilisation de l'opérateur Trident (manuellement ou à l'aide du graphique Helm) ou `tridentctl`. Avant d'installer ou de mettre à niveau Astra Trident, consultez le https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["systèmes front-end, systèmes back-end et configurations hôte pris en charge"^].

+
** *Système back-end de stockage Astra Trident configuré* : au moins un système back-end de stockage Astra Trident doit l'être https://docs.netapp.com/us-en/trident/trident-use/backends.html["configuré"^] sur le cluster.
** *Classes de stockage Astra Trident configurées* : au moins une classe de stockage Astra Trident doit être https://docs.netapp.com/us-en/trident/trident-use/manage-stor-class.html["configuré"^] sur le cluster. Si une classe de stockage par défaut est configurée, assurez-vous qu'une seule classe de stockage possède cette annotation.
** *Contrôleur de snapshot de volume Astra Trident et classe de snapshot de volume installés et configurés* : le contrôleur de snapshot de volume doit être https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploying-a-volume-snapshot-controller["installé"^] Il est ainsi possible de créer des snapshots dans Astra Control. Au moins un Astra Trident `VolumeSnapshotClass` a été https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#step-1-set-up-a-volumesnapshotclass["configuration"^] par un administrateur.




====
* *Astra Control Provisioner* : pour utiliser les fonctionnalités avancées de gestion et de provisionnement de stockage d'Astra Control Provisioner accessibles uniquement aux utilisateurs d'Astra Control, vous devez installer Astra Trident 23.10 ou version ultérieure et activer link:../use/enable-acp.html["Fonctionnalité Astra Control Provisioner"].


.Étapes
. Dans le Tableau de bord, sélectionnez *Manage Kubernetes cluster*.
+
Suivez les invites pour ajouter le cluster.

. *Fournisseur* : sélectionnez l'onglet *autre* pour ajouter des détails sur votre cluster auto-géré.
. *Autre*: Fournir des détails sur votre cluster auto-géré en téléchargeant un `kubeconfig.yaml` ou en collant le contenu du `kubeconfig.yaml` fichier à partir du presse-papiers.
+

NOTE: Si vous créez la vôtre `kubeconfig` fichier, vous ne devez définir que *un* élément de contexte dans celui-ci. Reportez-vous à la section link:create-kubeconfig.html["ces instructions"^] pour plus d'informations sur la création `kubeconfig` fichiers.

. *Nom d'identification* : indiquez un nom pour les informations d'identification de cluster autogérées que vous téléchargez sur Astra Control. Par défaut, le nom des identifiants est automatiquement renseigné comme nom du cluster.
. *Identificateur de route privée* : saisissez l'identificateur de route privée que vous pouvez obtenir à partir du connecteur Astra. Si vous interrogez le connecteur Astra via le `kubectl get astraconnector -n astra-connector` l'identificateur de route privée est appelé `ASTRACONNECTORID`.
+

NOTE: L'identifiant de la route privée est le nom associé à Astra Connector qui permet de gérer un cluster Kubernetes privé par Astra. Dans ce contexte, un cluster privé est un cluster Kubernetes qui n'expose pas son serveur d'API à Internet.

. Sélectionnez *Suivant*.
. (Facultatif) *Storage* : si vous le souhaitez, sélectionnez la classe de stockage que les applications Kubernetes déployées sur ce cluster doivent utiliser par défaut.
+
.. Pour sélectionner une nouvelle classe de stockage par défaut pour le cluster, cochez la case *affecter une nouvelle classe de stockage par défaut*.
.. Sélectionnez une nouvelle classe de stockage par défaut dans la liste.
+
[NOTE]
====
Chaque fournisseur de service de stockage cloud affiche les informations suivantes en matière de prix, de performance et de résilience :

ifdef::gcp[]

*** Cloud Volumes Service pour Google Cloud : informations sur le prix, la performance et la résilience
*** Google persistent Disk : pas d'informations sur le prix, la performance ou la résilience disponibles


endif::gcp[]

ifdef::azure[]

*** Azure NetApp Files : informations sur les performances et la résilience
*** Azure Managed Disks : aucun prix, performances ou résilience disponibles


endif::azure[]

ifdef::aws[]

*** Amazon Elastic Block Store : pas d'informations disponibles sur le prix, la performance ou la résilience
*** Amazon FSX pour NetApp ONTAP : aucune information disponible concernant le prix, les performances ou la résilience


endif::aws[]

*** NetApp Cloud Volumes ONTAP : aucune information disponible sur le prix, les performances ou la résilience


====
+
Chaque classe de stockage peut utiliser l'un des services suivants :





ifdef::gcp[]

* https://cloud.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service pour Google Cloud"^]
* https://cloud.google.com/persistent-disk/["Disque persistant Google"^]


endif::gcp[]

ifdef::azure[]

* https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview["Disques gérés Azure"^]


endif::azure[]

ifdef::aws[]

* https://docs.aws.amazon.com/ebs/["Amazon Elastic Block Store"^]
* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX pour NetApp ONTAP"^]


endif::aws[]

* https://www.netapp.com/cloud-services/cloud-volumes-ontap/what-is-cloud-volumes/["NetApp Cloud Volumes ONTAP"^]
+
En savoir plus sur link:../learn/aws-storage.html["Classes de stockage pour les clusters Amazon Web Services"]. En savoir plus sur link:../learn/azure-storage.html["Classes de stockage pour les clusters AKS"]. En savoir plus sur link:../learn/choose-class-and-size.html["Classes de stockage pour clusters GKE"].

+
.. Sélectionnez *Suivant*.
.. *Revoir et approuver* : consultez les détails de la configuration.
.. Sélectionnez *Ajouter* pour ajouter le cluster à Astra Control Service.






== Modifiez la classe de stockage par défaut

Vous pouvez modifier la classe de stockage par défaut d'un cluster.



=== Modifiez la classe de stockage par défaut avec Astra Control

Vous pouvez modifier la classe de stockage par défaut d'un cluster depuis Astra Control. Si votre cluster utilise un service back-end de stockage installé précédemment, il se peut que vous ne puissiez pas utiliser cette méthode pour modifier la classe de stockage par défaut (l'action *Set as default* n'est pas sélectionnable). Dans ce cas, vous pouvez <<Modifiez la classe de stockage par défaut à l'aide de la ligne de commande>>.

.Étapes
. Dans l'interface utilisateur du service de contrôle Astra, sélectionnez *clusters*.
. Sur la page *clusters*, sélectionnez le cluster que vous souhaitez modifier.
. Sélectionnez l'onglet *stockage*.
. Sélectionnez la catégorie *classes de stockage*.
. Sélectionnez le menu *actions* pour la classe de stockage que vous souhaitez définir par défaut.
. Sélectionnez *définir comme valeur par défaut*.




=== Modifiez la classe de stockage par défaut à l'aide de la ligne de commande

Vous pouvez modifier la classe de stockage par défaut d'un cluster à l'aide des commandes Kubernetes. Cette méthode fonctionne quelle que soit la configuration du cluster.

.Étapes
. Connectez-vous à votre cluster Kubernetes.
. Lister les classes de stockage de votre cluster :
+
[source, console]
----
kubectl get storageclass
----
. Supprimez la désignation par défaut de la classe de stockage par défaut. Remplacez <SC_NAME> par le nom de la classe de stockage :
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
----
. Sélectionnez par défaut une classe de stockage différente. Remplacez <SC_NAME> par le nom de la classe de stockage :
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
. Confirmez la nouvelle classe de stockage par défaut :
+
[source, console]
----
kubectl get storageclass
----


ifdef::azure[]
