---
sidebar: sidebar 
permalink: get-started/add-first-cluster.html 
keywords: discover cluster, add cluster, add kubernetes cluster, discover kubernetes cluster, add cluster 
summary: 'Une fois votre environnement configuré, vous êtes prêt à créer un cluster Kubernetes, puis à l"ajouter à Astra Control Service.' 
---
= Commencez à gérer les clusters Kubernetes à partir d'Astra Control Service
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Une fois votre environnement configuré, vous êtes prêt à créer un cluster Kubernetes, puis à l'ajouter à Astra Control Service.

* <<Créez un cluster Kubernetes>>
* <<Commencez à gérer les clusters Kubernetes>>
* <<Modifiez la classe de stockage par défaut>>




== Créez un cluster Kubernetes

Si vous ne disposez pas encore d'un cluster, vous pouvez en créer un qui rencontre link:set-up-amazon-web-services.html#eks-cluster-requirements["Exigences d'Astra Control Service pour Amazon Elastic Kubernetes Service (EKS)"]. Si vous ne disposez pas encore d'un cluster, vous pouvez en créer un qui rencontre link:set-up-google-cloud.html#gke-cluster-requirements["Exigences d'Astra Control Service pour Google Kubernetes Engine (GKE)"]. Si vous ne disposez pas encore d'un cluster, vous pouvez en créer un qui rencontre link:set-up-microsoft-azure-with-anf.html#azure-kubernetes-service-cluster-requirements["Astra Control Service exigences pour Azure Kubernetes Service (AKS) avec Azure NetApp Files"] ou link:set-up-microsoft-azure-with-amd.html#azure-kubernetes-service-cluster-requirements["Astra Control Service exigences pour Azure Kubernetes Service (AKS) avec des disques gérés Azure"].


NOTE: Astra Control Service prend en charge les clusters AKS qui utilisent Azure Active Directory (Azure AD) pour l'authentification et la gestion des identités. Une fois le cluster créé, suivez les instructions du https://docs.microsoft.com/en-us/azure/aks/managed-aad["documentation officielle"^] Pour configurer le cluster afin d'utiliser Azure AD. Vous devez vous assurer que vos clusters répondent aux exigences de l'intégration d'Azure AD gérée par AKS.

Vous pouvez ajouter un cluster auto-géré au service Astra Control en téléchargeant un `kubeconfig.yaml` fichier. Vous devez vous assurer que le cluster répond aux exigences décrites dans <<Commencez à gérer les clusters Kubernetes>>.



== Commencez à gérer les clusters Kubernetes

Une fois connecté au service Astra Control, la première étape consiste à commencer à gérer vos clusters. Vous pouvez ajouter un cluster géré par un fournisseur de cloud ou un cluster autogéré. Avant d'ajouter un cluster au service Astra Control, vous devez effectuer certaines tâches et vous assurer que le cluster répond à certaines exigences.

.Vous devez adopter une nouvelle version du modèle 8217;ll pour la gestion de clusters gérés par un fournisseur de services cloud
[%collapsible]
====
ifdef::aws[]

.Amazon Web Services
* Vous devez disposer du fichier JSON contenant les informations d'identification de l'utilisateur IAM qui a créé le cluster. link:../get-started/set-up-amazon-web-services.html#create-an-iam-user["Découvrez comment créer un utilisateur IAM"].
* Astra Trident est requis pour Amazon FSX pour NetApp ONTAP. Si vous prévoyez d'utiliser Amazon FSX pour NetApp ONTAP en tant que backend de stockage de votre cluster EKS, consultez les informations d'Astra Trident dans le link:set-up-amazon-web-services.html#eks-cluster-requirements["Configuration requise pour le cluster EKS"].
* (Facultatif) si vous devez fournir les informations nécessaires `kubectl` L'accès aux commandes d'un cluster à d'autres utilisateurs IAM qui ne sont pas le créateur du cluster, reportez-vous aux instructions de la https://aws.amazon.com/premiumsupport/knowledge-center/amazon-eks-cluster-access/["Comment puis-je fournir l'accès aux autres utilisateurs IAM et aux rôles après la création du cluster dans Amazon EKS ?"^].


endif::aws[]

ifdef::azure[]

.Microsoft Azure
* Vous devez disposer du fichier JSON qui contient la sortie de l'interface de ligne de commandes Azure lorsque vous avez créé le principal de service. link:../get-started/set-up-microsoft-azure-with-anf.html#create-an-azure-service-principal-2["Découvrez comment configurer un principal de service"].
+
Vous aurez également besoin de votre ID d'abonnement Azure, si vous n'avez pas ajouté le fichier JSON.

* Pour les clusters AKS privés, reportez-vous à la section link:manage-private-cluster.html["Gérer des clusters privés à partir d'Astra Control Service"^].
* Si vous prévoyez d'utiliser NetApp Cloud Volumes ONTAP en tant que système back-end de stockage, vous devez configurer Cloud Volumes ONTAP pour qu'il fonctionne avec Microsoft Azure. Consultez le Cloud Volumes ONTAP https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-azure.html["documentation de configuration"^].


endif::azure[]

ifdef::gcp[]

.Google Cloud
* Vous devez disposer du fichier de clé de compte de service pour un compte de service disposant des autorisations requises. link:../get-started/set-up-google-cloud.html#create-a-service-account["Découvrez comment configurer un compte de service"].
* Si vous prévoyez d'utiliser NetApp Cloud Volumes ONTAP en tant que système back-end de stockage, vous devez configurer Cloud Volumes ONTAP pour qu'il fonctionne avec Google Cloud. Consultez le Cloud Volumes ONTAP https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["documentation de configuration"^].


endif::gcp[]

====
.Ce que vous&#8217;ll avez besoin pour les clusters autogérés
[%collapsible]
====
Vos clusters autogérés peuvent utiliser Astra Trident pour communiquer avec les services de stockage NetApp, ou ils peuvent utiliser des pilotes CSI (Container Storage interface) pour interagir avec d'autres services de stockage.

Astra Control Service prend en charge les clusters autogérés avec les distributions Kubernetes suivantes :

* Plateforme de conteneurs Red Hat OpenShift
* Moteur rancher Kubernetes
* Kubernetes en amont


Votre cluster autogéré doit répondre aux exigences suivantes :

* Le cluster doit être accessible via Internet.
* Si vous utilisez ou prévoyez d'utiliser le stockage activé avec des pilotes CSI, les pilotes CSI appropriés doivent être installés sur le cluster. Pour plus d'informations sur l'utilisation des pilotes CSI pour intégrer le stockage, reportez-vous à la documentation de votre service de stockage.
* Si vous utilisez ou prévoyez d'utiliser un système de stockage NetApp, vérifiez que vous avez installé la dernière version d'Astra Trident :
+

NOTE: C'est possible https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html#choose-the-deployment-method["Déployez Astra Trident"^] Utilisation de l'opérateur Trident (manuellement ou à l'aide du graphique Helm) ou `tridentctl`. Avant d'installer ou de mettre à niveau Astra Trident, consultez le https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["systèmes front-end, systèmes back-end et configurations hôte pris en charge"^].

+
** *Système back-end de stockage Trident configuré* : au moins un système back-end de stockage Trident Astra doit être configuré https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-postdeployment.html#step-1-create-a-backend["configuré"^] sur le cluster.
** *Classes de stockage Trident configurées* : au moins une classe de stockage Astra Trident doit être https://docs.netapp.com/us-en/trident/trident-use/manage-stor-class.html["configuré"^] sur le cluster. Si une classe de stockage par défaut est configurée, assurez-vous qu'une seule classe de stockage possède cette annotation.
** *Contrôleur de snapshot de volume Astra Trident et classe de snapshot de volume installés et configurés* : le contrôleur de snapshot de volume doit être https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploying-a-volume-snapshot-controller["installé"^] Il est ainsi possible de créer des snapshots dans Astra Control. Au moins un Astra Trident `VolumeSnapshotClass` a été https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#step-1-set-up-a-volumesnapshotclass["configuration"^] par un administrateur.


* *Kubeconfig accessible*: Vous avez accès au <<kubeconfig,cluster kubeconfig>> qui ne comprend qu'un seul élément de contexte.
* *Rancher uniquement*: Lorsque vous gérez des clusters d'applications dans un environnement Rancher, modifiez le contexte par défaut du cluster d'applications dans le fichier kubeconfig fourni par Rancher pour utiliser un contexte de plan de contrôle au lieu du contexte du serveur d'API Rancher. La charge est réduite sur le serveur API Rancher et les performances sont améliorées.


.(Facultatif) Vérifiez la version Astra Trident
Si votre cluster utilise Astra Trident pour les services de stockage, vérifiez que la version installée d'Astra Trident est la plus récente.

.Étapes
. Vérifiez la version d'Astra Trident.
+
[source, console]
----
kubectl get tridentversions -n trident
----
+
Si Astra Trident est installé, le résultat est similaire à ce qui suit :

+
[listing]
----
NAME      VERSION
trident   22.10.0
----
+
Si Astra Trident n'est pas installé, le résultat est similaire à ce qui suit :

+
[listing]
----
error: the server doesn't have a resource type "tridentversions"
----
+

NOTE: Si Astra Trident n'est pas installé ou n'est pas à jour et que vous souhaitez que votre cluster utilise Astra Trident pour les services de stockage, vous devez installer la dernière version d'Astra Trident avant de poursuivre. Reportez-vous à la https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html["Documentation Astra Trident"^] pour obtenir des instructions.

. Assurez-vous que les pods fonctionnent :
+
[source, console]
----
kubectl get pods -n trident
----
. Vérifiez si les classes de stockage utilisent les pilotes Trident Astra pris en charge. Le nom de provisionnement doit être `csi.trident.netapp.io`. Reportez-vous à l'exemple suivant :
+
[source, console]
----
kubectl get sc
----
+
Exemple de réponse :

+
[listing]
----
NAME                   PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
ontap-gold (default)   csi.trident.netapp.io          Delete          Immediate           true                   5d23h
----


.Création d'un kubeconfig (s'applique aux clusters qui exécutent Rancher, OpenShift et Kubernetes en amont)
Avant d'effectuer les étapes suivantes, assurez-vous que vous disposez des éléments suivants sur votre machine :

* kubectl v1.19 ou version ultérieure installé
* Un kubeconfig actif avec des droits d'administrateur de cluster pour le contexte actif


.Étapes
. Créer un compte de service comme suit :
+
.. Créez un fichier de compte de service appelé `astracontrol-service-account.yaml`.
+
Ajustez le nom et l'espace de noms selon vos besoins. Si des modifications sont apportées ici, vous devez appliquer les mêmes modifications dans les étapes suivantes.

+
[source, subs="specialcharacters,quotes"]
----
*astracontrol-service-account.yaml*
----
+
[source, yaml]
----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: astracontrol-service-account
  namespace: default
----
.. Appliquer le compte de service :
+
[source, console]
----
kubectl apply -f astracontrol-service-account.yaml
----


. Accordez des autorisations d'administration du cluster comme suit :
+
.. Créer un `ClusterRoleBinding` fichier appelé `astracontrol-clusterrolebinding.yaml`.
+
Ajustez les noms et espaces de noms modifiés lors de la création du compte de service, le cas échéant.

+
[source, subs="specialcharacters,quotes"]
----
*astracontrol-clusterrolebinding.yaml*
----
+
[source, yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: astracontrol-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: astracontrol-service-account
  namespace: default
----
.. Appliquer la liaison de rôle de cluster :
+
[source, console]
----
kubectl apply -f astracontrol-clusterrolebinding.yaml
----


. Indiquez les secrets du compte de service, en les remplaçant `<context>` avec le contexte approprié pour votre installation :
+
[source, console]
----
kubectl get serviceaccount astracontrol-service-account --context <context> --namespace default -o json
----
+
La fin de la sortie doit ressembler à ce qui suit :

+
[listing]
----
"secrets": [
{ "name": "astracontrol-service-account-dockercfg-vhz87"},
{ "name": "astracontrol-service-account-token-r59kr"}
]
----
+
Les indices pour chaque élément dans `secrets` la matrice commence par 0. Dans l'exemple ci-dessus, l'index de `astracontrol-service-account-dockercfg-vhz87` serait 0 et l'index pour `astracontrol-service-account-token-r59kr` serait 1. Dans votre résultat, notez l'index du nom du compte de service qui contient le mot "jeton".

. Générez le kubeconfig comme suit :
+
.. Créer un `create-kubeconfig.sh` fichier. Remplacement `TOKEN_INDEX` au début du script suivant avec la valeur correcte.
+
[source, subs="specialcharacters,quotes"]
----
*create-kubeconfig.sh*
----
+
[source, console]
----
# Update these to match your environment.
# Replace TOKEN_INDEX with the correct value
# from the output in the previous step. If you
# didn't change anything else above, don't change
# anything else here.

SERVICE_ACCOUNT_NAME=astracontrol-service-account
NAMESPACE=default
NEW_CONTEXT=astracontrol
KUBECONFIG_FILE='kubeconfig-sa'

CONTEXT=$(kubectl config current-context)

SECRET_NAME=$(kubectl get serviceaccount ${SERVICE_ACCOUNT_NAME} \
  --context ${CONTEXT} \
  --namespace ${NAMESPACE} \
  -o jsonpath='{.secrets[TOKEN_INDEX].name}')
TOKEN_DATA=$(kubectl get secret ${SECRET_NAME} \
  --context ${CONTEXT} \
  --namespace ${NAMESPACE} \
  -o jsonpath='{.data.token}')

TOKEN=$(echo ${TOKEN_DATA} | base64 -d)

# Create dedicated kubeconfig
# Create a full copy
kubectl config view --raw > ${KUBECONFIG_FILE}.full.tmp

# Switch working context to correct context
kubectl --kubeconfig ${KUBECONFIG_FILE}.full.tmp config use-context ${CONTEXT}

# Minify
kubectl --kubeconfig ${KUBECONFIG_FILE}.full.tmp \
  config view --flatten --minify > ${KUBECONFIG_FILE}.tmp

# Rename context
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  rename-context ${CONTEXT} ${NEW_CONTEXT}

# Create token user
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  set-credentials ${CONTEXT}-${NAMESPACE}-token-user \
  --token ${TOKEN}

# Set context to use token user
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  set-context ${NEW_CONTEXT} --user ${CONTEXT}-${NAMESPACE}-token-user

# Set context to correct namespace
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  set-context ${NEW_CONTEXT} --namespace ${NAMESPACE}

# Flatten/minify kubeconfig
kubectl config --kubeconfig ${KUBECONFIG_FILE}.tmp \
  view --flatten --minify > ${KUBECONFIG_FILE}

# Remove tmp
rm ${KUBECONFIG_FILE}.full.tmp
rm ${KUBECONFIG_FILE}.tmp
----
.. Source des commandes à appliquer à votre cluster Kubernetes.
+
[source, console]
----
source create-kubeconfig.sh
----


. (Facultatif) Renommer le kubeconfig pour nommer votre cluster. Protéger les informations d'identification du cluster.
+
[listing]
----
chmod 700 create-kubeconfig.sh
mv kubeconfig-sa.txt YOUR_CLUSTER_NAME_kubeconfig
----


====
.Étapes
. Dans le Tableau de bord, sélectionnez *Manage Kubernetes cluster*.
+
Suivez les invites pour ajouter le cluster.

. *Fournisseur* : sélectionnez votre fournisseur de cloud, puis fournissez les informations d'identification requises pour créer une nouvelle instance de cloud ou sélectionnez une instance de cloud existante à utiliser.


ifdef::aws[]

. *Amazon Web Services*: Fournissez des détails sur votre compte utilisateur Amazon Web Services IAM en téléchargeant un fichier JSON ou en collant le contenu de ce fichier JSON à partir de votre presse-papiers.
+
Le fichier JSON doit contenir les informations d'identification de l'utilisateur IAM qui a créé le cluster.



endif::aws[]

ifdef::azure[]

. *Microsoft Azure*: Fournissez des détails sur votre entité de service Azure en téléchargeant un fichier JSON ou en collant le contenu de ce fichier JSON à partir de votre presse-papiers.
+
Le fichier JSON doit contenir la sortie de l'interface de ligne de commandes Azure lorsque vous avez créé le principal de service. Il peut également inclure votre identifiant d'abonnement afin qu'il soit automatiquement ajouté à Astra. Sinon, vous devez saisir manuellement l'ID après avoir fourni le fichier JSON.



endif::azure[]

ifdef::gcp[]

. *Google Cloud Platform*: Fournir le fichier de clé de compte de service soit en téléchargeant le fichier ou en collant le contenu à partir de votre presse-papiers.
+
Astra Control Service utilise le compte de service pour détecter les clusters qui s'exécutent dans Google Kubernetes Engine.



endif::gcp[]

. *Autre*: Fournir des détails sur votre cluster auto-géré en téléchargeant un `kubeconfig.yaml` ou en collant le contenu du `kubeconfig.yaml` fichier à partir du presse-papiers.
+

NOTE: Si vous créez la vôtre `kubeconfig` fichier, vous ne devez définir que *un* élément de contexte dans celui-ci. Reportez-vous à la section https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["Documentation Kubernetes"^] pour plus d'informations sur la création `kubeconfig` fichiers.

+
.. *Nom de l'instance de Cloud* (pour les clusters gérés par le fournisseur) : indiquez un nom pour la nouvelle instance de Cloud qui sera créée lors de l'ajout de ce cluster. En savoir plus sur link:../use/manage-cloud-instances.html["instances cloud"].
+

NOTE: Lorsque vous sélectionnez dans la liste des clusters, faites attention à l'onglet éligible. Si un avertissement s'affiche, passez le curseur de la souris sur l'avertissement pour déterminer si un problème est lié au cluster. Par exemple, il peut identifier que le cluster ne dispose pas d'un nœud worker.





ifdef::azure[]

+


NOTE: Si vous sélectionnez un cluster marqué d'une icône « privé », il utilise des adresses IP privées et le connecteur Astra est nécessaire pour que Astra Control gère le cluster. Si vous voyez un message indiquant que vous devez installer le connecteur Astra, link:manage-private-cluster.html["reportez-vous à ces instructions"] Pour installer le connecteur Astra et permettre la gestion du cluster. Après avoir installé le connecteur Astra, le cluster doit être admissible et vous pouvez procéder à l'ajout du cluster.

endif::azure[]

. *Credential name* (pour les clusters autogérés) : indiquez un nom pour les informations d'identification du cluster autogérées que vous téléchargez sur Astra Control. Par défaut, le nom des identifiants est automatiquement renseigné comme nom du cluster.
. (Facultatif) *stockage* : sélectionnez la classe de stockage que vous souhaitez déployer par défaut pour les applications Kubernetes sur ce cluster.
+
[NOTE]
====
Chaque fournisseur de service de stockage cloud affiche les informations suivantes en matière de prix, de performance et de résilience :

ifdef::gcp[]

** Cloud Volumes Service pour Google Cloud : informations sur le prix, la performance et la résilience
** Google persistent Disk : pas d'informations sur le prix, la performance ou la résilience disponibles


endif::gcp[]

ifdef::azure[]

** Azure NetApp Files : informations sur les performances et la résilience
** Azure Managed Disks : aucun prix, performances ou résilience disponibles


endif::azure[]

ifdef::aws[]

** Amazon Elastic Block Store : pas d'informations disponibles sur le prix, la performance ou la résilience
** Amazon FSX pour NetApp ONTAP : aucune information disponible concernant le prix, les performances ou la résilience


endif::aws[]

** NetApp Cloud Volumes ONTAP : aucune information disponible sur le prix, les performances ou la résilience


====
+
Chaque classe de stockage peut utiliser l'un des services suivants :



ifdef::gcp[]

* https://cloud.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service pour Google Cloud"^]
* https://cloud.google.com/persistent-disk/["Disque persistant Google"^]


endif::gcp[]

ifdef::azure[]

* https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview["Disques gérés Azure"^]


endif::azure[]

ifdef::aws[]

* https://docs.aws.amazon.com/ebs/["Amazon Elastic Block Store"^]
* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX pour NetApp ONTAP"^]


endif::aws[]

* https://www.netapp.com/cloud-services/cloud-volumes-ontap/what-is-cloud-volumes/["NetApp Cloud Volumes ONTAP"^]
+
En savoir plus sur link:../learn/aws-storage.html["Classes de stockage pour les clusters Amazon Web Services"]. En savoir plus sur link:../learn/azure-storage.html["Classes de stockage pour les clusters AKS"]. En savoir plus sur link:../learn/choose-class-and-size.html["Classes de stockage pour clusters GKE"].

+
.. *Review & Approve* : consultez les détails de la configuration et sélectionnez *Add cluster*.




.Résultat
*Pour les clusters gérés par le fournisseur* : s'il s'agit du premier cluster que vous avez ajouté pour ce fournisseur de cloud, Astra Control Service crée un magasin d'objets pour le fournisseur de cloud pour les sauvegardes des applications exécutées sur des clusters éligibles. (Lorsque vous ajoutez des clusters suivants pour ce fournisseur de cloud, aucun magasin d'objets n'est créé.) Si vous avez spécifié une classe de stockage par défaut, Astra Control Service définit la classe de stockage par défaut que vous avez spécifiée. Pour les clusters gérés dans Amazon Web Services ou Google Cloud Platform, Astra Control Service crée également un compte d'administration sur le cluster. Ces actions peuvent prendre plusieurs minutes.



== Modifiez la classe de stockage par défaut

Vous pouvez modifier la classe de stockage par défaut d'un cluster.



=== Modifiez la classe de stockage par défaut avec Astra Control

Vous pouvez modifier la classe de stockage par défaut d'un cluster depuis Astra Control. Si votre cluster utilise un service back-end de stockage installé précédemment, il se peut que vous ne puissiez pas utiliser cette méthode pour modifier la classe de stockage par défaut (l'action *Set as default* n'est pas sélectionnable). Dans ce cas, vous pouvez <<Modifiez la classe de stockage par défaut à l'aide de la ligne de commande>>.

.Étapes
. Dans l'interface utilisateur du service de contrôle Astra, sélectionnez *clusters*.
. Sur la page *clusters*, sélectionnez le cluster que vous souhaitez modifier.
. Sélectionnez l'onglet *stockage*.
. Sélectionnez la catégorie *classes de stockage*.
. Sélectionnez le menu *actions* pour la classe de stockage que vous souhaitez définir par défaut.
. Sélectionnez *définir comme valeur par défaut*.




=== Modifiez la classe de stockage par défaut à l'aide de la ligne de commande

Vous pouvez modifier la classe de stockage par défaut d'un cluster à l'aide des commandes Kubernetes. Cette méthode fonctionne quelle que soit la configuration du cluster.

.Étapes
. Connectez-vous à votre cluster Kubernetes.
. Lister les classes de stockage de votre cluster :
+
[source, console]
----
kubectl get storageclass
----
. Supprimez la désignation par défaut de la classe de stockage par défaut. Remplacez <SC_NAME> par le nom de la classe de stockage :
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
----
. Sélectionnez par défaut une classe de stockage différente. Remplacez <SC_NAME> par le nom de la classe de stockage :
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
. Confirmez la nouvelle classe de stockage par défaut :
+
[source, console]
----
kubectl get storageclass
----


ifdef::azure[]



== Pour en savoir plus

* link:manage-private-cluster.html["Gérer un cluster privé"]


endif::azure[]
