---
sidebar: sidebar 
permalink: get-started/add-first-cluster.html 
keywords: discover cluster, add cluster, add kubernetes cluster, discover kubernetes cluster, add cluster 
summary: 'Une fois votre environnement configuré, vous êtes prêt à créer un cluster Kubernetes, puis à l"ajouter à Astra Control Service.' 
---
= Commencez à gérer les clusters Kubernetes à partir d'Astra Control Service
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Une fois votre environnement configuré, vous êtes prêt à créer un cluster Kubernetes, puis à l'ajouter à Astra Control Service.

* <<Créez un cluster Kubernetes>>
* <<Commencez à gérer les clusters Kubernetes>>
* <<Modifiez la classe de stockage par défaut>>




== Créez un cluster Kubernetes

Si vous ne disposez pas encore d'un cluster, vous pouvez en créer un qui rencontre link:set-up-amazon-web-services.html#eks-cluster-requirements["Exigences d'Astra Control Service pour Amazon Elastic Kubernetes Service (EKS)"]. Si vous ne disposez pas encore d'un cluster, vous pouvez en créer un qui rencontre link:set-up-google-cloud.html#gke-cluster-requirements["Exigences d'Astra Control Service pour Google Kubernetes Engine (GKE)"]. Si vous ne disposez pas encore d'un cluster, vous pouvez en créer un qui rencontre link:set-up-microsoft-azure-with-anf.html#azure-kubernetes-service-cluster-requirements["Astra Control Service exigences pour Azure Kubernetes Service (AKS) avec Azure NetApp Files"] ou link:set-up-microsoft-azure-with-amd.html#azure-kubernetes-service-cluster-requirements["Astra Control Service exigences pour Azure Kubernetes Service (AKS) avec des disques gérés Azure"].


NOTE: Astra Control Service prend en charge les clusters AKS qui utilisent Azure Active Directory (Azure AD) pour l'authentification et la gestion des identités. Une fois le cluster créé, suivez les instructions du https://docs.microsoft.com/en-us/azure/aks/managed-aad["documentation officielle"^] Pour configurer le cluster afin d'utiliser Azure AD. Vous devez vous assurer que vos clusters répondent aux exigences de l'intégration d'Azure AD gérée par AKS.



=== Clusters autogérés

Un cluster autogéré est un cluster que vous provisionnez et gérez directement. ASTRA Control Service prend en charge les clusters autogérés qui s'exécutent dans un environnement de cloud public. Vous pouvez ajouter un cluster auto-géré au service Astra Control en téléchargeant un `kubeconfig.yaml` fichier. Vous devez vous assurer que le cluster répond aux exigences décrites dans <<Commencez à gérer les clusters Kubernetes>>.



== Commencez à gérer les clusters Kubernetes

Une fois connecté au service Astra Control, la première étape consiste à commencer à gérer vos clusters. Vous pouvez ajouter un cluster géré par un fournisseur de cloud ou un cluster autogéré. Avant d'ajouter un cluster à Astra Control Service, vous devez effectuer des tâches spécifiques et vous assurer qu'il répond à certaines exigences.

.Vous devez adopter une nouvelle version du modèle 8217;ll pour la gestion de clusters gérés par un fournisseur de services cloud
[%collapsible]
====
ifdef::aws[]

.Amazon Web Services
* Vous devez disposer du fichier JSON contenant les informations d'identification de l'utilisateur IAM qui a créé le cluster. link:../get-started/set-up-amazon-web-services.html#create-an-iam-user["Découvrez comment créer un utilisateur IAM"].
* Astra Trident est requis pour Amazon FSX pour NetApp ONTAP. Si vous prévoyez d'utiliser Amazon FSX pour NetApp ONTAP en tant que backend de stockage de votre cluster EKS, consultez les informations d'Astra Trident dans le link:set-up-amazon-web-services.html#eks-cluster-requirements["Configuration requise pour le cluster EKS"].
* (Facultatif) si vous devez fournir les informations nécessaires `kubectl` L'accès aux commandes d'un cluster à d'autres utilisateurs IAM qui ne sont pas le créateur du cluster, reportez-vous aux instructions de la https://aws.amazon.com/premiumsupport/knowledge-center/amazon-eks-cluster-access/["Comment puis-je fournir l'accès aux autres utilisateurs IAM et aux rôles après la création du cluster dans Amazon EKS ?"^].
* Si vous prévoyez d'utiliser NetApp Cloud Volumes ONTAP en tant que système back-end de stockage, vous devez configurer Cloud Volumes ONTAP pour qu'il fonctionne avec Amazon Web Services. Consultez le Cloud Volumes ONTAP https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html["documentation de configuration"^].


endif::aws[]

ifdef::azure[]

.Microsoft Azure
* Vous devez disposer du fichier JSON qui contient la sortie de l'interface de ligne de commandes Azure lorsque vous avez créé le principal de service. link:../get-started/set-up-microsoft-azure-with-anf.html#create-an-azure-service-principal-2["Découvrez comment configurer un principal de service"].
+
Vous aurez également besoin de votre ID d'abonnement Azure, si vous n'avez pas ajouté le fichier JSON.

* Pour les clusters AKS privés, reportez-vous à la section link:manage-private-cluster.html["Gérer des clusters privés à partir d'Astra Control Service"^].
* Si vous prévoyez d'utiliser NetApp Cloud Volumes ONTAP en tant que système back-end de stockage, vous devez configurer Cloud Volumes ONTAP pour qu'il fonctionne avec Microsoft Azure. Consultez le Cloud Volumes ONTAP https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-azure.html["documentation de configuration"^].


endif::azure[]

ifdef::gcp[]

.Google Cloud
* Vous devez disposer du fichier de clé de compte de service pour un compte de service disposant des autorisations requises. link:../get-started/set-up-google-cloud.html#create-a-service-account["Découvrez comment configurer un compte de service"].
* Si vous prévoyez d'utiliser NetApp Cloud Volumes ONTAP en tant que système back-end de stockage, vous devez configurer Cloud Volumes ONTAP pour qu'il fonctionne avec Google Cloud. Consultez le Cloud Volumes ONTAP https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["documentation de configuration"^].


endif::gcp[]

====
.Ce que vous&#8217;ll avez besoin pour les clusters autogérés
[%collapsible]
====
Un cluster autogéré est un cluster que vous provisionnez et gérez directement. ASTRA Control Service prend en charge les clusters autogérés qui s'exécutent dans un environnement de cloud public. Vos clusters autogérés peuvent utiliser Astra Trident pour s'interfacer avec les services de stockage NetApp ou les pilotes Container Storage interface (CSI) pour s'interfacer avec Amazon Elastic Block Store (EBS), les disques gérés Azure et le service Google persistent Disk.

ASTRA Control Service prend en charge les clusters autogérés qui utilisent les distributions Kubernetes suivantes :

* Plateforme de conteneurs Red Hat OpenShift
* Moteur rancher Kubernetes
* Kubernetes en amont


Votre cluster autogéré doit répondre aux exigences suivantes :

* Le cluster doit être accessible via Internet.
* Le cluster ne peut pas être hébergé sur votre réseau sur site ; il doit être hébergé dans un environnement de cloud public.
* Si vous utilisez ou prévoyez d'utiliser le stockage activé avec des pilotes CSI, les pilotes CSI appropriés doivent être installés sur le cluster. Pour plus d'informations sur l'utilisation des pilotes CSI pour intégrer le stockage, reportez-vous à la documentation de votre service de stockage.
* Vous avez accès au fichier kubeconfig du cluster qui ne contient qu'un seul élément de contexte. Suivre link:create-kubeconfig.html["ces instructions"^] pour générer un fichier kubeconfig de rôle de cluster admin.
* *Rancher uniquement*: Lorsque vous gérez des clusters d'applications dans un environnement Rancher, modifiez le contexte par défaut du cluster d'applications dans le fichier kubeconfig fourni par Rancher pour utiliser un contexte de plan de contrôle au lieu du contexte du serveur d'API Rancher. La charge est réduite sur le serveur API Rancher et les performances sont améliorées.
* *Astra Trident* : si vous utilisez ou prévoyez d'utiliser le stockage NetApp, assurez-vous d'avoir installé la dernière version d'Astra Trident. Si Astra Trident est déjà installé, link:check-astra-trident-version.html["vérifiez qu'il s'agit de la dernière version"^].
+

NOTE: C'est possible https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html#choose-the-deployment-method["Déployez Astra Trident"^] Utilisation de l'opérateur Trident (manuellement ou à l'aide du graphique Helm) ou `tridentctl`. Avant d'installer ou de mettre à niveau Astra Trident, consultez le https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["systèmes front-end, systèmes back-end et configurations hôte pris en charge"^].

+
** *Système back-end de stockage Astra Trident configuré* : au moins un système back-end de stockage Astra Trident doit l'être https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-postdeployment.html#step-1-create-a-backend["configuré"^] sur le cluster.
** *Classes de stockage Astra Trident configurées* : au moins une classe de stockage Astra Trident doit être https://docs.netapp.com/us-en/trident/trident-use/manage-stor-class.html["configuré"^] sur le cluster. Si une classe de stockage par défaut est configurée, assurez-vous qu'une seule classe de stockage possède cette annotation.
** *Contrôleur de snapshot de volume Astra Trident et classe de snapshot de volume installés et configurés* : le contrôleur de snapshot de volume doit être https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#deploying-a-volume-snapshot-controller["installé"^] Il est ainsi possible de créer des snapshots dans Astra Control. Au moins un Astra Trident `VolumeSnapshotClass` a été https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html#step-1-set-up-a-volumesnapshotclass["configuration"^] par un administrateur.




====
.Étapes
. Dans le Tableau de bord, sélectionnez *Manage Kubernetes cluster*.
+
Suivez les invites pour ajouter le cluster.

. *Fournisseur* : sélectionnez votre fournisseur de cloud, puis fournissez les informations d'identification requises pour créer une nouvelle instance de cloud ou sélectionnez une instance de cloud existante à utiliser.


ifdef::aws[]

. *Amazon Web Services*: Fournissez des détails sur votre compte utilisateur Amazon Web Services IAM en téléchargeant un fichier JSON ou en collant le contenu de ce fichier JSON à partir de votre presse-papiers.
+
Le fichier JSON doit contenir les informations d'identification de l'utilisateur IAM qui a créé le cluster.



endif::aws[]

ifdef::azure[]

. *Microsoft Azure*: Fournissez des détails sur votre entité de service Azure en téléchargeant un fichier JSON ou en collant le contenu de ce fichier JSON à partir de votre presse-papiers.
+
Le fichier JSON doit contenir la sortie de l'interface de ligne de commandes Azure lorsque vous avez créé le principal de service. Il peut également inclure votre identifiant d'abonnement afin qu'il soit automatiquement ajouté à Astra. Sinon, vous devez saisir manuellement l'ID après avoir fourni le fichier JSON.



endif::azure[]

ifdef::gcp[]

. *Google Cloud Platform*: Fournir le fichier de clé de compte de service soit en téléchargeant le fichier ou en collant le contenu à partir de votre presse-papiers.
+
Astra Control Service utilise le compte de service pour détecter les clusters qui s'exécutent dans Google Kubernetes Engine.



endif::gcp[]

. *Autre*: Fournir des détails sur votre cluster auto-géré en téléchargeant un `kubeconfig.yaml` ou en collant le contenu du `kubeconfig.yaml` fichier à partir du presse-papiers.
+

NOTE: Si vous créez la vôtre `kubeconfig` fichier, vous ne devez définir que *un* élément de contexte dans celui-ci. Reportez-vous à la section https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["Documentation Kubernetes"^] pour plus d'informations sur la création `kubeconfig` fichiers.

+
.. *Nom de l'instance de Cloud* (pour les clusters gérés par le fournisseur) : indiquez un nom pour la nouvelle instance de Cloud qui sera créée lors de l'ajout de ce cluster. En savoir plus sur link:../use/manage-cloud-instances.html["instances cloud"].
+

NOTE: Lorsque vous sélectionnez dans la liste des clusters, faites attention à l'onglet éligible. Si un avertissement s'affiche, passez le curseur de la souris sur l'avertissement pour déterminer si un problème est lié au cluster. Par exemple, il peut identifier que le cluster ne dispose pas d'un nœud worker.





ifdef::azure[]

+


NOTE: Si vous sélectionnez un cluster marqué d'une icône « privé », il utilise des adresses IP privées et le connecteur Astra est nécessaire pour que Astra Control gère le cluster. Si vous voyez un message indiquant que vous devez installer le connecteur Astra, link:manage-private-cluster.html["reportez-vous à ces instructions"] Pour installer le connecteur Astra et permettre la gestion du cluster. Après avoir installé le connecteur Astra, le cluster doit être admissible et vous pouvez procéder à l'ajout du cluster.

endif::azure[]

. *Credential name* (pour les clusters autogérés) : indiquez un nom pour les informations d'identification du cluster autogérées que vous téléchargez sur Astra Control. Par défaut, le nom des identifiants est automatiquement renseigné comme nom du cluster.
. (Facultatif) *ID de route privée* : saisissez l'identifiant de route privée que vous pouvez obtenir à partir du connecteur Astra.
+

NOTE: L'ID de route privée est le nom associé à Astra Connector qui permet de gérer un cluster Kubernetes privé par Astra. Dans ce contexte, un cluster privé est un cluster Kubernetes qui n'expose pas son serveur d'API à Internet.

. (Facultatif) *stockage* : sélectionnez la classe de stockage que vous souhaitez déployer par défaut pour les applications Kubernetes sur ce cluster.
+
[NOTE]
====
Chaque fournisseur de service de stockage cloud affiche les informations suivantes en matière de prix, de performance et de résilience :

ifdef::gcp[]

** Cloud Volumes Service pour Google Cloud : informations sur le prix, la performance et la résilience
** Google persistent Disk : pas d'informations sur le prix, la performance ou la résilience disponibles


endif::gcp[]

ifdef::azure[]

** Azure NetApp Files : informations sur les performances et la résilience
** Azure Managed Disks : aucun prix, performances ou résilience disponibles


endif::azure[]

ifdef::aws[]

** Amazon Elastic Block Store : pas d'informations disponibles sur le prix, la performance ou la résilience
** Amazon FSX pour NetApp ONTAP : aucune information disponible concernant le prix, les performances ou la résilience


endif::aws[]

** NetApp Cloud Volumes ONTAP : aucune information disponible sur le prix, les performances ou la résilience


====
+
Chaque classe de stockage peut utiliser l'un des services suivants :



ifdef::gcp[]

* https://cloud.netapp.com/cloud-volumes-service-for-gcp["Cloud Volumes Service pour Google Cloud"^]
* https://cloud.google.com/persistent-disk/["Disque persistant Google"^]


endif::gcp[]

ifdef::azure[]

* https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview["Disques gérés Azure"^]


endif::azure[]

ifdef::aws[]

* https://docs.aws.amazon.com/ebs/["Amazon Elastic Block Store"^]
* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX pour NetApp ONTAP"^]


endif::aws[]

* https://www.netapp.com/cloud-services/cloud-volumes-ontap/what-is-cloud-volumes/["NetApp Cloud Volumes ONTAP"^]
+
En savoir plus sur link:../learn/aws-storage.html["Classes de stockage pour les clusters Amazon Web Services"]. En savoir plus sur link:../learn/azure-storage.html["Classes de stockage pour les clusters AKS"]. En savoir plus sur link:../learn/choose-class-and-size.html["Classes de stockage pour clusters GKE"].

+
.. *Review & Approve* : consultez les détails de la configuration et sélectionnez *Add cluster*.




.Résultat
*Pour les clusters gérés par le fournisseur* : s'il s'agit du premier cluster que vous avez ajouté pour ce fournisseur de cloud, Astra Control Service crée un magasin d'objets pour le fournisseur de cloud pour les sauvegardes des applications exécutées sur des clusters éligibles. (Lorsque vous ajoutez des clusters suivants pour ce fournisseur de cloud, aucun magasin d'objets n'est créé.) Si vous avez spécifié une classe de stockage par défaut, Astra Control Service définit la classe de stockage par défaut que vous avez spécifiée. Pour les clusters gérés dans Amazon Web Services ou Google Cloud Platform, Astra Control Service crée également un compte d'administration sur le cluster. Ces actions peuvent prendre plusieurs minutes.



== Modifiez la classe de stockage par défaut

Vous pouvez modifier la classe de stockage par défaut d'un cluster.



=== Modifiez la classe de stockage par défaut avec Astra Control

Vous pouvez modifier la classe de stockage par défaut d'un cluster depuis Astra Control. Si votre cluster utilise un service back-end de stockage installé précédemment, il se peut que vous ne puissiez pas utiliser cette méthode pour modifier la classe de stockage par défaut (l'action *Set as default* n'est pas sélectionnable). Dans ce cas, vous pouvez <<Modifiez la classe de stockage par défaut à l'aide de la ligne de commande>>.

.Étapes
. Dans l'interface utilisateur du service de contrôle Astra, sélectionnez *clusters*.
. Sur la page *clusters*, sélectionnez le cluster que vous souhaitez modifier.
. Sélectionnez l'onglet *stockage*.
. Sélectionnez la catégorie *classes de stockage*.
. Sélectionnez le menu *actions* pour la classe de stockage que vous souhaitez définir par défaut.
. Sélectionnez *définir comme valeur par défaut*.




=== Modifiez la classe de stockage par défaut à l'aide de la ligne de commande

Vous pouvez modifier la classe de stockage par défaut d'un cluster à l'aide des commandes Kubernetes. Cette méthode fonctionne quelle que soit la configuration du cluster.

.Étapes
. Connectez-vous à votre cluster Kubernetes.
. Lister les classes de stockage de votre cluster :
+
[source, console]
----
kubectl get storageclass
----
. Supprimez la désignation par défaut de la classe de stockage par défaut. Remplacez <SC_NAME> par le nom de la classe de stockage :
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
----
. Sélectionnez par défaut une classe de stockage différente. Remplacez <SC_NAME> par le nom de la classe de stockage :
+
[source, console]
----
kubectl patch storageclass <SC_NAME> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
. Confirmez la nouvelle classe de stockage par défaut :
+
[source, console]
----
kubectl get storageclass
----


ifdef::azure[]



== Pour en savoir plus

* link:manage-private-cluster.html["Gérer un cluster privé"]


endif::azure[]
