---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: introduction, how astra works, how Astra works, what Astra is, concept, understanding, overview 
summary: 'Astra Control est une solution de gestion du cycle de vie des données applicatives Kubernetes qui simplifie les opérations des applications avec état. Protégez, sauvegardez et migrez facilement les workloads Kubernetes, et créez instantanément des clones d"applications de travail.' 
---
= Découvrez Astra Control
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Control est une solution de gestion du cycle de vie des données applicatives Kubernetes qui simplifie les opérations des applications avec état. Protégez, sauvegardez et migrez facilement les workloads Kubernetes, et créez instantanément des clones d'applications de travail.



== Caractéristiques

Astra Control offre des fonctionnalités stratégiques pour la gestion du cycle de vie des données d'application Kubernetes :

* Gérez automatiquement le stockage persistant
* Création de copies Snapshot et de sauvegardes à la demande intégrant la cohérence applicative
* Automatisation des opérations de sauvegarde et de snapshots basées sur des règles
* Migrez des applications et des données d'un cluster Kubernetes vers un autre
* Réplication d'applications sur un système distant à l'aide de la technologie NetApp SnapMirror (Astra Control Center)
* Clonage d'applications de la phase de transfert à la production
* Visualiser l'état de santé et de protection des applications
* Implémentation de vos workflows de sauvegarde et de migration à l'aide d'une interface utilisateur web ou d'une API




== Modèles de déploiement

Astra Control est disponible dans deux modèles de déploiement :

* *Astra Control Service* : service géré par NetApp qui permet de gérer les données intégrant la cohérence applicative de clusters Kubernetes dans plusieurs environnements de fournisseurs cloud, ainsi que des clusters Kubernetes autogéré.
* *Astra Control Center* : logiciel autogéré qui assure une gestion des données compatible avec les applications de clusters Kubernetes exécutés dans votre environnement sur site. Astra Control Center peut également être installé sur plusieurs environnements de fournisseur cloud avec un système back-end de stockage NetApp Cloud Volumes ONTAP.


[cols="1h,2d,2a"]
|===
|  | Service Astra Control | Centre de contrôle Astra 


| Comment est-elle proposée ? | En tant que service cloud entièrement géré de NetApp  a| 
En tant que logiciel que vous pouvez télécharger, installer et gérer



| Où est-il hébergé ? | Dans le cloud public de votre choix  a| 
Sur votre cluster Kubernetes



| Comment est-elle mise à jour ? | Géré par NetApp  a| 
Vous gérez toutes les mises à jour



| Quelles sont les distributions Kubernetes prises en charge ?  a| 
* *Fournisseurs de cloud*
+
** Amazon Web Services
+
*** Amazon Elastic Kubernetes Service (EKS)


** Google Cloud
+
*** Google Kubernetes Engine (GKE)


** Microsoft Azure
+
*** Azure Kubernetes Service (AKS)




* *Clusters autogérés*
+
** Kubernetes (en amont)
** Rancher Kubernetes Engine (RKE)
** Plateforme de conteneurs Red Hat OpenShift


* *Clusters sur site*
+
** Red Hat OpenShift Container Platform sur site



 a| 
* Azure Kubernetes Service sur Azure Stack HCI
* Anthos de Google
* Kubernetes (en amont)
* Rancher Kubernetes Engine (RKE)
* Plateforme de conteneurs Red Hat OpenShift




| Quels sont les systèmes back-end pris en charge ?  a| 
* *Fournisseurs de cloud*
+
** Amazon Web Services
+
*** Amazon EBS
*** Amazon FSX pour NetApp ONTAP
*** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["Cloud Volumes ONTAP"^]


** Google Cloud
+
*** Disque persistant Google
*** NetApp Cloud Volumes Service
*** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["Cloud Volumes ONTAP"^]


** Microsoft Azure
+
*** Disques gérés Azure
*** Azure NetApp Files
*** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-azure.html["Cloud Volumes ONTAP"^]




* *Clusters autogérés*
+
** Amazon EBS
** Disques gérés Azure
** Disque persistant Google
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]
** NetApp MetroCluster
** https://longhorn.io/["Longhorn"^]


* *Clusters sur site*
+
** NetApp MetroCluster
** Systèmes NetApp ONTAP AFF et FAS
** NetApp ONTAP Select
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]
** https://longhorn.io/["Longhorn"^]



 a| 
* Systèmes NetApp ONTAP AFF et FAS
* NetApp ONTAP Select
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]
* https://longhorn.io/["Longhorn"^]


|===


== Fonctionnement du service Astra Control

Astra Control Service est un service cloud géré par NetApp qui est constamment disponible et mis à jour avec les dernières fonctionnalités. Elle utilise plusieurs composants pour faciliter la gestion du cycle de vie des données des applications.

À un niveau élevé, le service de contrôle Astra fonctionne comme suit :

* Commencez avec le service Astra Control en configurant votre fournisseur de services cloud et en vous inscrivant à un compte Astra.


ifdef::gcp[]

+ ** pour les clusters GKE, Astra Control Service utilise https://cloud.netapp.com/cloud-volumes-service-for-gcp["NetApp Cloud Volumes Service pour Google Cloud"^] Ou des disques persistants Google en tant que système de stockage back-end pour vos volumes persistants.

endif::gcp[]

ifdef::azure[]

+ ** pour les grappes AKS, Astra Control Service utilise https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^] Ou des disques gérés Azure en tant que backend de stockage pour les volumes persistants.

endif::azure[]

ifdef::aws[]

+ ** pour les clusters Amazon EKS, Astra Control Service utilise https://docs.aws.amazon.com/ebs/["Amazon Elastic Block Store"^] ou https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX pour NetApp ONTAP"^] en tant que système back-end de stockage pour vos volumes persistants.

endif::aws[]

* Vous ajoutez votre première solution de calcul Kubernetes à Astra Control Service. Le service de contrôle d'Astra procède ensuite aux opérations suivantes :
+
** Crée un magasin d'objets sur votre compte de fournisseur cloud, où sont stockées les copies de sauvegarde.




ifdef::azure[]

+ dans Azure, Astra Control Service crée également un groupe de ressources, un compte de stockage et des clés pour le conteneur Blob.

endif::azure[]

* Crée un nouveau rôle d'administrateur et un compte de service Kubernetes sur le cluster.
* Utilise ce nouveau rôle d'administration pour installer le lien../concepts/architecture#astra-control-components[astra Control Provisioner] sur le cluster et pour créer une ou plusieurs classes de stockage.
* Si vous utilisez une offre de stockage de service cloud NetApp comme système back-end de stockage, Astra Control Service utilise Astra Control provisionner pour provisionner des volumes persistants pour vos applications. Si vous utilisez des disques gérés Amazon EBS ou Azure comme système de stockage principal, vous devez installer un pilote CSI spécifique au fournisseur. Les instructions d'installation sont fournies dans le link:set-up-amazon-web-services.html["Configurer Amazon Web Services"^] et link:set-up-microsoft-azure-with-amd.html["Configuration de Microsoft Azure avec des disques gérés Azure"^].
+
** À ce stade, vous pouvez définir des applications à partir de votre cluster. Les volumes persistants seront provisionnés sur le back-end de stockage via la nouvelle classe de stockage par défaut.
** Utilisez ensuite le service Astra Control pour gérer ces applications, et commencez à créer des copies Snapshot, des sauvegardes et des clones.




Le plan gratuit d'Astra Control vous permet de gérer jusqu'à 10 espaces de noms dans votre compte. Si vous souhaitez gérer plus de 10 espaces de noms, vous devrez configurer la facturation en passant du Plan gratuit au Plan Premium.



== Fonctionnement du centre de contrôle Astra

Astra Control Center fonctionne localement dans votre propre cloud privé.

ASTRA Control Center prend en charge des clusters Kubernetes avec une classe de stockage configurée par Astra Control Provisioner et un système de stockage back-end ONTAP.

Dans un environnement connecté au cloud, Astra Control Center utilise Cloud Insights pour fournir des fonctionnalités avancées de surveillance et de télémétrie. En l'absence de connexion Cloud Insights, un contrôle et une télémétrie limités (7 jours de metrics) sont disponibles dans Astra Control Center, mais aussi exportés vers les outils de surveillance natifs de Kubernetes (comme Prometheus et Grafana) via des points de terminaison ouverts.

Astra Control Center est entièrement intégré à l'écosystème AutoSupport et Active IQ. Il fournit aux utilisateurs et au support NetApp des informations relatives à la résolution de problèmes et à l'utilisation.

Vous pouvez essayer Astra Control Center avec une licence d'évaluation de 90 jours. La version d'évaluation est prise en charge par courrier électronique et par les options de communauté. Vous avez également accès aux articles et à la documentation de la base de connaissances à partir du tableau de bord de support des produits.

Pour installer et utiliser Astra Control Center, vous devez vous en assurer https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html["de formation"].

À un niveau élevé, le centre de contrôle Astra ressemble à ce qui suit :

* Vous installez Astra Control Center dans votre environnement local. En savoir plus https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html["Poser le centre de contrôle Astra"].
* Vous avez effectué certaines tâches de configuration, telles que :
+
** Configuration des licences.
** Ajoutez votre premier cluster.
** Ajout du stockage back-end découvert lorsque vous avez ajouté le cluster
** Ajoutez un compartiment de magasin d'objets pour stocker vos sauvegardes d'applications.




En savoir plus https://docs.netapp.com/us-en/astra-control-center/get-started/setup_overview.html["Configurer le centre de contrôle Astra"].

Vous pouvez ajouter des applications à votre cluster. Si certaines applications sont déjà gérées dans le cluster, vous pouvez aussi utiliser Astra Control Center pour les gérer. Utilisez ensuite Astra Control Center pour créer des copies Snapshot, des sauvegardes, des clones et des relations de réplication.



== Pour en savoir plus

* https://docs.netapp.com/us-en/astra-family/["Documentation de la gamme de produits NetApp Astra"^]
* https://docs.netapp.com/us-en/astra-control-center/index.html["Documentation Astra Control Center"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["Documentation de l'API Astra Control"^]
* https://docs.netapp.com/us-en/trident/index.html["Documentation Astra Trident"^]
* https://docs.netapp.com/us-en/cloudinsights/["Documentation Cloud Insights"^]
* https://docs.netapp.com/us-en/ontap/index.html["Documentation ONTAP"^]

