---
sidebar: sidebar 
permalink: get-started/register.html 
keywords: BlueXP, sign up, log in, login, register, register for BlueXP, create account, sign up for account, get an account, account, accounts 
summary: 'ASTRA Control Service est intégré au service d"authentification de NetApp BlueXP. Inscrivez-vous à BlueXP pour accéder à Astra Control Service et aux autres services cloud de NetApp.' 
---
= Créez un compte de service Astra Control
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Pour utiliser Astra Control Service, vous devez disposer d'un compte Astra Control Service associé à votre compte NetApp BlueXP. Effectuez le processus d'enregistrement d'Astra Control Service, puis, si vous ne possédez pas encore de compte BlueXP, inscrivez-vous à BlueXP pour accéder à Astra Control Service.



== Créez un compte Astra Control

Avant de pouvoir vous connecter au service Astra Control, vous devez effectuer un processus d'inscription pour obtenir un compte Astra Control Service.

Lorsque vous utilisez Astra Control Service, vous gérerez vos applications à partir d'un compte. Un compte comprend les utilisateurs qui peuvent afficher et gérer les applications du compte, ainsi que vos détails de facturation.

.Étapes
. https://cloud.netapp.com/astra["Accédez à la page Astra Control sur BlueXP"^].
. Sélectionnez *s'inscrire pour le plan gratuit*.
. Fournissez les informations requises dans le formulaire.
+
Quelques points importants à prendre en compte lorsque vous remplissez le formulaire :

+
** Votre nom d'entreprise et votre adresse doivent être précis car nous les vérifions afin de répondre aux exigences de la conformité aux règlements du commerce international.
** Le *Nom de compte Astra* est le nom du compte de service de contrôle Astra de votre entreprise. Vous verrez ce nom dans l'interface utilisateur du service de contrôle Astra. Notez que vous pouvez créer des comptes supplémentaires (jusqu'à 5), si nécessaire.
** Dans le champ *adresse e-mail professionnelle*, si vous disposez d'un compte NetApp BlueXP, saisissez ici l'adresse e-mail que vous utilisez pour ce compte. Si vous ne possédez pas encore de compte NetApp BlueXP, utilisez l'adresse e-mail que vous entrez ici lorsque vous vous inscrivez à BlueXP.


. Sélectionnez *Créer un compte*.




== Inscrivez-vous à BlueXP

ASTRA Control Service est intégré au service d'authentification de NetApp BlueXP. Vous pouvez vous connecter à NetApp BlueXP à l'aide de vos identifiants BlueXP ou du site de support NetApp. Si vous ne possédez pas encore de compte NetApp BlueXP ou sur le site de support NetApp, inscrivez-vous à BlueXP pour accéder à Astra Control Service et aux autres services cloud de NetApp. Si vous possédez déjà un compte BlueXP ou sur le site de support NetApp et que vous avez terminé votre inscription, vous pouvez accéder à https://astra.netapp.io["Service Astra Control"^] Directement à l'aide de vos identifiants BlueXP ou du site de support NetApp.


TIP: Vous pouvez également utiliser l'authentification unique pour vous connecter à BlueXP à l'aide d'identifiants de votre annuaire d'entreprise (identité fédérée). Pour en savoir plus, consultez le https://cloud.netapp.com/help-center["Centre d'assistance"^] Puis sélectionnez *Options de connexion à Cloud Central*.

.Étapes
. Accédez à https://cloud.netapp.com["NetApp BlueXP"^].
. En haut à droite, sélectionnez *commencer*.
. Sélectionnez *s'inscrire*.
. Remplissez le formulaire.
+
Assurez-vous que le numéro de téléphone et l'adresse e-mail que vous avez saisis sont les mêmes que ceux que vous avez utilisés dans le formulaire d'inscription à Astra Control précédent.

. Sélectionnez *s'inscrire*.
+

TIP: L'adresse e-mail que vous saisissez dans ces formulaires est destinée à votre identifiant utilisateur NetApp BlueXP. Utilisez cet ID d'utilisateur BlueXP lorsque vous créez un compte Astra Control ou lorsqu'un administrateur Astra Control vous invite à un compte Astra Control existant.

. Attendez la réception d'un e-mail depuis NetApp BlueXP. L'e-mail provient de l'adresse saas.support@netapp.com et peut prendre plusieurs minutes. Assurez-vous de vérifier votre dossier de courrier indésirable.
. Une fois l'e-mail reçu, sélectionnez le lien dans l'e-mail pour vérifier votre adresse e-mail.


.Résultat
Vous disposez désormais d'un identifiant BlueXP actif.

Maintenant que vous êtes enregistré, vous pouvez accéder à Astra Control directement à l'aide de vos identifiants BlueXP depuis https://astra.netapp.io[].
